#ifndef __CTSYMBOL_H__
#define __CTSYMBOL_H__

/*=============================================================================
// Symbol construction, segment extraction and comparison
//===========================================================================*/
#define ADDRESS_OFFSET        30
#define ADDRESS_MASK          0x3
#define OBJECT_OFFSET         20
#define OBJECT_MASK           0x03FF
#define VENDOR_OFFSET         10
#define VENDOR_MASK           0x03FF
#define ITEM_OFFSET           0
#define ITEM_MASK             0x03FF

// Build a symbol.
/*  Symbol name looks like: Obj_VENDOR_ItemName
	Object  for which this symbol was defined
	Vendor who assigned the name and value for this symbol
	Item Name for this particular symbol.
*/
#define CTkvs_Sym( object, vendor, item )\
	(CTsymbol)(((OBJECT_MASK & (object)) << OBJECT_OFFSET) |\
		   ((VENDOR_MASK & (vendor)) << VENDOR_OFFSET) |\
		    (  ITEM_MASK &   (item)))


#define CTkvs_Object( symbol )\
	(CTuint)(((symbol) >> OBJECT_OFFSET) & OBJECT_MASK)
#define CTkvs_Vendor( symbol )\
	(CTuint)(((symbol) >> VENDOR_OFFSET) & VENDOR_MASK)
#define CTkvs_Item( symbol )\
	(CTuint)(((symbol) >>   ITEM_OFFSET) &   ITEM_MASK)

#define CTsym_Build        CTkvs_Sym
#define CTsym_Object       CTkvs_Object
#define CTsym_Vendor       CTkvs_Vendor
#define CTsym_Item         CTkvs_Item

/******************************************************************************
 *    ECTF defined symbol object values.
 *****************************************************************************/
#define CT_objANY                (0x0000)       /* ANY OBJECT */
#define CT_objCONFERENCE         (0x0001)       /* CONFERENCE */
#define CT_objCONNECTION         (0x0002)       /* CONNECTION */
#define CT_objCONTAINER          (0x0003)       /* CONTAINER */
#define CT_objFAXRECEIVER        (0x0004)       /* FAX RECEIVER */
#define CT_objFAXSENDER          (0x0005)       /* FAX SENDER */
#define CT_objFAXSERVICE         (0x0006)       /* FAX SERVICE */
#define CT_objGROUP              (0x0007)       /* GROUP */
#define CT_objKVSET              (0x0008)       /* KVSET */
#define CT_objMACRO              (0x0009)       /* MACRO */
#define CT_objPLAYER             (0x000A)       /* PLAYER */
#define CT_objRECORDER           (0x000B)       /* RECORDER */
#define CT_objSCR                (0x000C)       /* SCR */
#define CT_objSESSION            (0x000D)       /* SESSION */
#define CT_objSIGD               (0x000E)       /* SIGNAL DETECTOR */
#define CT_objSIGG               (0x000F)       /* SIGNAL GENERATOR */
#define CT_objASR                (0x0010)       /* ASR */
#define CT_objADMIN              (0x0011)       /* ADMINISTRATION */
#define CT_objCCR                (0x0012)       /* CCR */
#define CT_objDATAOBJECT         (0x0013)       /* CONT DATA OBJECT */
#define CT_objMESSAGE            (0x0014)       /* MESSAGE */
#define CT_objFAXLL              (0x0015)       /* FAX LOW LEVEL */
#define CT_objERROR              (0x0016)       /* ERROR */
#define CT_objSESSIONMANAGER     (0x0018)       /* SESSION MANAGER */
#define CT_objSYMBOL             (0x0019)       /* SYMBOL TABLE */
#define CT_objTRIGGER            (0x001A)       /* EVENT TRIGGER */
#define CT_objMEDIA              (0x001B)       /* media server symbol */
#define CT_objPROFILE            (0x001C)       /* profile module*/
#define CT_objCOMMUNICATION      (0x001D)
#define CT_objSIA                (0x001E)       /* Service Interface Adapter */
#define CT_objAUTHEN             (0x001F)       /* authen module,Walker */
#define CT_objCOMMCTRL		 (0x0020)
#define CT_objSWITCH		 (0X0021)
#define CT_objMAINT              (0X0022)
#define CT_objCONFIG             (0X0023)
#define CT_objSCHEDULER          (0X0024)       /* Scheduler,Walker */
#define CT_objSS7				(0x0025)

#define CT_objPUBLIC		 (0X0080)

#define CT_objAPPLICATION        (0x00F0)       /* Local Application */

/******************************************************************************
 *    ECTF defined symbol vendor values.
 *****************************************************************************/
 
#define CT_vendECTF                    (0x0001)
#define CT_vendDLGC                    (0x0002)
#define CT_vendTELSUN		       (0x0003)
#define CT_vendEXCEL		       (0x0004)	

/******************************************************************************
 *    Definitions of standard errors.
 *****************************************************************************/
#define __CTErrorSym(item)             CTsym_Build( CT_objERROR,\
						  CT_vendECTF,\
                                                  (item))

#define CT_errorOK                                          __CTErrorSym(0x000)
#define CT_errorBadGroup                                    __CTErrorSym(0x001)
#define CT_errorBadGroupConfig                              __CTErrorSym(0x002)
#define CT_errorBadGroupSet                                 __CTErrorSym(0x003)
#define CT_errorBadParm                                     __CTErrorSym(0x004)
#define CT_errorBadResource                                 __CTErrorSym(0x005)
#define CT_errorBadRTC                                      __CTErrorSym(0x006)
#define CT_errorBadSession                                  __CTErrorSym(0x007)
#define CT_errorBusy                                        __CTErrorSym(0x008)
#define CT_errorSystem                                      __CTErrorSym(0x009)
#define CT_errorTimeout                                     __CTErrorSym(0x00A)
#define CT_errorStopped                                     __CTErrorSym(0x00B)
#define CT_errorNoMem                                       __CTErrorSym(0x00C)
#define CT_errorTransNotStopped                             __CTErrorSym(0x00D) 
#define CT_errorNotOwner                                    __CTErrorSym(0x00E)
#define CT_errorBadContainerName                            __CTErrorSym(0x00F)
#define CT_errorBadObjectName                               __CTErrorSym(0x010)
#define CT_errorContainerExists                             __CTErrorSym(0x011)
#define CT_errorContainerNotExist                           __CTErrorSym(0x012)
#define CT_errorInvalidParameter                            __CTErrorSym(0x013)
#define CT_errorObjectExists                                __CTErrorSym(0x014)
#define CT_errorObjectNotExist                              __CTErrorSym(0x015)
#define CT_errorContainerFull                               __CTErrorSym(0x016)
#define CT_errorObjectFull                                  __CTErrorSym(0x017)
#define CT_errorLocked                                      __CTErrorSym(0x018)
#define CT_errorInvPosition                                 __CTErrorSym(0x019)
#define CT_errorPermission                                  __CTErrorSym(0x01A)
#define CT_errorBadKVSet                                    __CTErrorSym(0x01B)
#define CT_errorBadKey                                      __CTErrorSym(0x01C)
#define CT_errorKeyNotFound                                 __CTErrorSym(0x01D)
#define CT_errorBadValueType                                __CTErrorSym(0x01E)
#define CT_errorNullArray                                   __CTErrorSym(0x01F)
#define CT_errorValueIsArray                                __CTErrorSym(0x020)
#define CT_errorValueNotArray                               __CTErrorSym(0x021)
#define CT_errorNotSupported                                __CTErrorSym(0x022)                 
#define CT_errorInvalidOp                                   __CTErrorSym(0x023)
#define CT_errorBadObjectHandle                             __CTErrorSym(0x024)
#define CT_errorEndOfStream                                 __CTErrorSym(0x025)
#define CT_errorMediaChange                                 __CTErrorSym(0x026)
#define CT_errorBadArg                                      __CTErrorSym(0x027)
#define CT_errorNoTranStopped                               __CTErrorSym(0x029)
#define CT_errorBadParmValue                                __CTErrorSym(0x02A)
#define CT_errorNotOnStack                                  __CTErrorSym(0x02B)
#define CT_errorShuttingDown                                __CTErrorSym(0x02C)
#define CT_errorStartOfStream                               __CTErrorSym(0x02D)
#define CT_errorBadMediaType                                __CTErrorSym(0x02E)
#define CT_errorNotAnswered                                 __CTErrorSym(0x02F)
#define CT_errorCouldNotDrop                                __CTErrorSym(0x030)
#define CT_errorDisconnected                                __CTErrorSym(0x031)
#define CT_errorOutOfService                                __CTErrorSym(0x032)
#define CT_errorNoDonor                                     __CTErrorSym(0x033)
#define CT_errorBadASI                                      __CTErrorSym(0x034)
#define CT_errorUnconnectable                               __CTErrorSym(0x035)
#define CT_errorNotFound                                    __CTErrorSym(0x036)
#define CT_errorBadData                                     __CTErrorSym(0x037)
#define CT_errorBadParameters                               __CTErrorSym(0x039)
#define CT_errorNoBandWidth                                 __CTErrorSym(0x03A)
#define CT_errorBufferTooSmall                              __CTErrorSym(0x03B)
#define CT_errorDirectionality                              __CTErrorSym(0x03C)
#define CT_errorMissingSymTable                             __CTErrorSym(0x03E)
#define CT_errorUnknownKey                                  __CTErrorSym(0x03F)
#define CT_errorBadHandle                                   __CTErrorSym(0x040)
#define CT_errorDupHandler                                  __CTErrorSym(0x041)
#define CT_errorBadEvent                                    __CTErrorSym(0x042)
#define CT_errorBadServer                                   __CTErrorSym(0x043)
#define CT_errorComms                                       __CTErrorSym(0x044)
#define CT_errorHandlerNotFound                             __CTErrorSym(0x045)
#define CT_errorBadAddress                                  __CTErrorSym(0x046)
#define CT_errorClientFailed                                __CTErrorSym(0x047)
#define CT_errorServerFailed                                __CTErrorSym(0x048)
#define CT_errorBandWidthMismatch                           __CTErrorSym(0x049)
#define CT_errorFileNotFound                                __CTErrorSym(0x04A)
#define CT_errorNumSignals                                  __CTErrorSym(0x04B)
#define CT_errorNotAvailable                                __CTErrorSym(0x04C)
#define CT_errorNoReceiver                                  __CTErrorSym(0x04D)
#define CT_errorTooManyProfs                                __CTErrorSym(0x04E)
#define CT_errorExists                                      __CTErrorSym(0x04F)
#define CT_errorExportError                                 __CTErrorSym(0x050) 
#define CT_errorCantOpenFile                                __CTErrorSym(0x051)   
#define CT_errorImportError                                 __CTErrorSym(0x052)
#define CT_errorBadName                                     __CTErrorSym(0x053)
#define CT_errorInvalidCallState                            __CTErrorSym(0x054)
#define CT_errorNoConnections                               __CTErrorSym(0x055)
#define CT_errorBadSide                                     __CTErrorSym(0x056)
#define CT_errorResourcesUnavailable                        __CTErrorSym(0x057)
#define CT_errorUnableToHandoff                             __CTErrorSym(0x058)
#define CT_errorNoDeviceAvailable                           __CTErrorSym(0x059)
#define CT_errorNoRuleMatched                               __CTErrorSym(0x05A)
#define CT_errorNoConsultationCall                          __CTErrorSym(0x05B)
#define CT_errorCallDropped                                 __CTErrorSym(0x05C)
#define CT_errorNoRequests                                  __CTErrorSym(0x05D)
#define CT_errorBadProfile                                  __CTErrorSym(0x05E)
#define CT_errorBadObjectList                               __CTErrorSym(0x05F)
#define CT_errorBadContext                                  __CTErrorSym(0x060)
#define CT_errorIncorrectContext                            __CTErrorSym(0x061)
#define CT_errorNoExists                                    __CTErrorSym(0x062)
#define CT_errorSignalID                                    __CTErrorSym(0x063)
#define CT_errorInvalidProfileName                          __CTErrorSym(0x064)
#define CT_errorASRFULL                                     __CTErrorSym(0x065)
#define CT_errorLINEERROR                                   __CTErrorSym(0x066)
#define CT_errorEndOfKey                                    __CTErrorSym(0x067)
#define CT_errorBadMemory                                   __CTErrorSym(0x068)
#define CT_errorKeyExists				    __CTErrorSym(0x069)
#define CT_errorBadStatus				    __CTErrorSym(0x06A)
#define CT_errorUnallocatedNumber            __CTTELSUNErrorSym(0x06c)
/////////////////////////////////////////////////////////////////////////////
#define __CTTELSUNErrorSym(item)             CTsym_Build( CT_objERROR,\
							  CT_vendTELSUN,\
							  (item))
#define CT_errorQueueInvaliable              __CTTELSUNErrorSym(0x001)
#define CT_errorPutQueueMsg                  __CTTELSUNErrorSym(0x002)
#define CT_errorShmInvaliable                __CTTELSUNErrorSym(0x003)
#define CT_errorCreateThread       	     __CTTELSUNErrorSym(0x004)
#define CT_errorNullData	   	     __CTTELSUNErrorSym(0x005)
#define CT_errorGetQueueMsg	   	     __CTTELSUNErrorSym(0x006)
#define CT_errorAccept		             __CTTELSUNErrorSym(0x007)
#define CT_errorDisconnect         	     __CTTELSUNErrorSym(0x008)
#define CT_errorBadReceiver        	     __CTTELSUNErrorSym(0x009)
#define CT_errorConnect  	   	     __CTTELSUNErrorSym(0x00A)
#define CT_errorTCPRegister        	     __CTTELSUNErrorSym(0x00B)

#define CT_errorFAIL			     __CTTELSUNErrorSym(0x00C)
#define CT_errorSessionFree                  __CTTELSUNErrorSym(0x00D) //Walker
//-------------------   add by zg  10/22/98
#define CT_errorMsgQueueWarn         __CTTELSUNErrorSym(0x00E)
#define CT_errorQUEUEFULL			__CTTELSUNErrorSym(0x010)
#define CT_errorTCBPAUSE			__CTTELSUNErrorSym(0x011)

///////////////////////////
/*****container error*****/
///////////////////////////
#define CT_errorContOpen                     __CTTELSUNErrorSym(0x051)
#define CT_errorContBadFormat                __CTTELSUNErrorSym(0x052)
#define CT_errorContEmpty                    __CTTELSUNErrorSym(0x053)
#define CT_errorContNoRoom                   __CTTELSUNErrorSym(0x054)
#define CT_errorContLock                     __CTTELSUNErrorSym(0x055)
#define CT_errorContBadHeader                __CTTELSUNErrorSym(0x056)
#define CT_errorContNotReaded                __CTTELSUNErrorSym(0x057)
#define CT_errorContIndexOutofBound          __CTTELSUNErrorSym(0x058)
#define CT_errorContProtected                __CTTELSUNErrorSym(0x059)
#define CT_errorContNotFound                 __CTTELSUNErrorSym(0x060)
#define CT_errorInValidOperate               __CTTELSUNErrorSym(0x061)
#define CT_errorContNotEmpty                 __CTTELSUNErrorSym(0x062)

#define CT_errorBadParmPriRscNotExist		     __CTTELSUNErrorSym(0x0070)
#define CT_errorBadParmSessionID	     __CTTELSUNErrorSym(0x0071)
#define CT_errorBadParmRscRepeat	     __CTTELSUNErrorSym(0x0072)
#define CT_errorSpcAlloc		     __CTTELSUNErrorSym(0x0073)
#define CT_errorNoPriRscInGroup		     __CTTELSUNErrorSym(0x0074)
#define CT_errorRscInsert		     __CTTELSUNErrorSym(0x0075)
#define CT_errorIntendToReleasePriRsc	     __CTTELSUNErrorSym(0x0076)

#define CT_errorRscNotFound		     __CTTELSUNErrorSym(0x0077)
#define CT_errorSpcConnect		     __CTTELSUNErrorSym(0x0078)
#define CT_errorNoMixFileInMem		    __CTTELSUNErrorSym(0x0079)
#define CT_errorHardWareOperate	     __CTTELSUNErrorSym(0x0070)

#define CT_errorRscHandleEvent		     __CTTELSUNErrorSym(0x0069)

#define CT_errorMediaHandleEvent	     __CTTELSUNErrorSym(0x0068)

#define CT_errorSpcHandleEvent		     __CTTELSUNErrorSym(0x0067)

#define CT_errorSpcStop			     __CTTELSUNErrorSym(0x0066)

#define CT_errorDeviceIOError                __CTTELSUNErrorSym(0x081)
#define CT_errorLoopCurrentOff               __CTTELSUNErrorSym(0x082)
#define CT_errorErrorEventHappened           __CTTELSUNErrorSym(0x083)
#define CT_errorBadEventBlock                __CTTELSUNErrorSym(0x084)
#define CT_errorUnknownEvent                 __CTTELSUNErrorSym(0x085)
#define CT_errorUserStopIt                   __CTTELSUNErrorSym(0x086)
#define CT_errorMaxSilencePassed	     __CTTELSUNErrorSym(0x087)

/*****************************************************************************
 * Error Data Used by Authen - Walker 98-02-27
 *****************************************************************************/

#define CT_errorNoData                       __CTTELSUNErrorSym(0x100)
#define CT_errorGetCellData                  __CTTELSUNErrorSym(0x101)
#define CT_errorPutCellData                  __CTTELSUNErrorSym(0x102)

/******************************************************************************
 *    Definitions of well known keys.                                    
 *****************************************************************************/

#define __CTAnySym(item)               CTsym_Build( CT_objANY,\
                                                    CT_vendECTF,\
                                                    (item))                

#define Any_ECTF_Null                                      __CTAnySym(0x000 )
#define Any_ECTF_Standard                                  __CTAnySym(0x100 )
#define Any_ECTF_Stop                                      __CTAnySym(0x101 )
#define Any_ECTF_Duration                                  __CTAnySym(0x102 )


/******************************************************************************
 * Redundant definitions - temporary
 *****************************************************************************/
                                                                         
#define CT_symbolNULL                  Any_ECTF_Null                     
                                                                         
                                                                         
/******************************************************************************
 *    KV Set Reserved Keys                                               
 *****************************************************************************/
                                                                         
#define __CTKVSSym(item)               CTsym_Build( CT_objKVSET,\
                                                    CT_vendECTF,\
                                                    (item))                
                                                                         
#define KVS_ECTF_FirstKey                                     __CTKVSSym(0x000)
#define KVS_ECTF_EOKeys                                       __CTKVSSym(0x001)


/******************************************************************************
 *    Connection symbols.                                                
 *****************************************************************************/
                                                                         
#define __CTConnSym(item)              CTsym_Build( CT_objCONNECTION,\
                                                    CT_vendECTF,\
                                                    (item) )               
                                                                         
#define Conn_ECTF_Create                                     __CTConnSym(0x000)
#define Conn_ECTF_GetParameters                              __CTConnSym(0x001)
#define Conn_ECTF_Destroy                                    __CTConnSym(0x002)
#define Conn_ECTF_Make                                       __CTConnSym(0x003)
#define Conn_ECTF_SetParameters                              __CTConnSym(0x004)
#define Conn_ECTF_Break                                      __CTConnSym(0x005)
#define Conn_ECTF_Directionality                             __CTConnSym(0x006)
#define Conn_ECTF_ToTarget                                   __CTConnSym(0x007)
#define Conn_ECTF_FromTarget                                 __CTConnSym(0x008)
#define Conn_ECTF_Default                                    __CTConnSym(0x009)
#define Conn_ECTF_ConnectionHandle                           __CTConnSym(0x00A)
#define Conn_ECTF_Parms                                      __CTConnSym(0x00B)
#define Conn_ECTF_ConnType                                   __CTConnSym(0x00C)
#define Conn_ECTF_Left                                       __CTConnSym(0x00D)
#define Conn_ECTF_Right                                      __CTConnSym(0x00E)
#define Conn_ECTF_ConnectTo                                  __CTConnSym(0x00F)
#define Conn_ECTF_Connect                                    __CTConnSym(0x010)
#define Conn_ECTF_Disconnect                                 __CTConnSym(0x011)

//following was 0x012. Conn_ECTF_ConnectToGroup now same as Conn_ECTF_Create
#define Conn_ECTF_ConnectToGroup                             __CTConnSym(0x000)
//following was 0x013. Conn_ECTF_DisconnectFromGroup now same as Conn_ECTF_Destroy
#define Conn_ECTF_DisconnectFromGroup                        __CTConnSym(0x002)

#define Conn_ECTF_UniDirectional                             __CTConnSym(0x014)
#define Conn_ECTF_Enabled                                    __CTConnSym(0x015)
#define Conn_ECTF_Side                                       __CTConnSym(0x016)

                                                                         
/******************************************************************************
 *    Symbol symbols.                                                    
 *****************************************************************************/
                                                                         
#define __CTSymbolSym(item)            CTsym_Build( CT_objSYMBOL,\
                                                    CT_vendECTF,\
                                                    (item) )               
                                                                         
#define Symbol_ECTF_LoadTable                              __CTSymbolSym(0x001)	


/******************************************************************************
 *    SCR symbols.
 *****************************************************************************/

#define __CTSCRSym(item)               CTsym_Build( CT_objSCR,\
						    CT_vendECTF,\
						    (item) )

#define SCR_ECTF_ASI                                          __CTSCRSym(0x001)
#define SCR_ECTF_Timeout                                      __CTSCRSym(0x002)
#define SCR_ECTF_ParmList                                     __CTSCRSym(0x003)
#define SCR_ECTF_HandMeOff                                    __CTSCRSym(0x004)
#define SCR_ECTF_Tag                                          __CTSCRSym(0x005)
#define SCR_ECTF_DropCall                                     __CTSCRSym(0x006)
#define SCR_ECTF_AnswerCall                                   __CTSCRSym(0x007)
#define SCR_ECTF_HandOff                                      __CTSCRSym(0x008)
#define SCR_ECTF_MakeConsultationCall                         __CTSCRSym(0x009)
#define SCR_ECTF_UnreceivedCount                              __CTSCRSym(0x00A)
#define SCR_ECTF_DestAddress                                  __CTSCRSym(0x00B)
#define SCR_ECTF_OrigGroup                                    __CTSCRSym(0x00C)
#define SCR_ECTF_DestGroup                                    __CTSCRSym(0x00D)
#define SCR_ECTF_Config                                       __CTSCRSym(0x00E)
#define SCR_ECTF_Group                                        __CTSCRSym(0x00F)
#define SCR_ECTF_SessionAddr                                  __CTSCRSym(0x010)
#define SCR_ECTF_MakeCall                                     __CTSCRSym(0x011)
#define SCR_ECTF_TransferCall                                 __CTSCRSym(0x012)
#define SCR_ECTF_RequestGroup                                 __CTSCRSym(0x013)
#define SCR_ECTF_AdvertCount                                  __CTSCRSym(0x014)
#define SCR_ECTF_AppProfile                                   __CTSCRSym(0x015)
#define SCR_ECTF_GroupConfig                                  __CTSCRSym(0x016)
#define SCR_ECTF_GroupSet                                     __CTSCRSym(0x017)
#define SCR_ECTF_AppProfName                                  __CTSCRSym(0x018)
#define SCR_ECTF_ASIName                                      __CTSCRSym(0x019)
#define SCR_ECTF_OrigAddress                                  __CTSCRSym(0x01A)
#define SCR_ECTF_SendMessage                                  __CTSCRSym(0x01B)
#define SCR_ECTF_NumRings                                     __CTSCRSym(0x01C)

/******************************************************************************
 *    CCR symbols.
 *****************************************************************************/

#define __CTCCRSym(item)               CTsym_Build( CT_objCCR,\
						    CT_vendECTF,\
						    (item) )

#define CCR_ECTF_ResClass                                     __CTCCRSym(0x001)
#define CCR_ECTF_Active                                       __CTCCRSym(0x002)
#define CCR_ECTF_Idle                                         __CTCCRSym(0x003)
#define CCR_ECTF_Hold                                         __CTCCRSym(0x004)
#define CCR_ECTF_ProviderType                                 __CTCCRSym(0x005)
#define CCR_ECTF_ServiceProviderId                            __CTCCRSym(0x006)
#define CCR_ECTF_DeviceName                                   __CTCCRSym(0x007)
#define CCR_ECTF_State                                        __CTCCRSym(0x008)
#define CCR_ECTF_NonIdleTime                                  __CTCCRSym(0x009)
#define CCR_ECTF_StateChange                                  __CTCCRSym(0x010)


/******************************************************************************
 *    Message symbols.
 *****************************************************************************/
#define __CTMsgSym(item)               CTsym_Build( CT_objMESSAGE,\
                                                    CT_vendECTF,\
                                                    (item))

#define Message_ECTF_SessionID                               __CTMsgSym (0x000)       
#define Message_ECTF_EventID                                 __CTMsgSym (0x001)       
#define Message_ECTF_Status                                  __CTMsgSym (0x002)       
#define Message_ECTF_Error                                   __CTMsgSym (0x003)       
#define Message_ECTF_SubError                                __CTMsgSym (0x004)       
#define Message_ECTF_EventQualifier                          __CTMsgSym (0x005)
#define Message_ECTF_ObjectID                                __CTMsgSym (0x006)
#define Message_ECTF_ObjectClass                             __CTMsgSym (0x007)
#define Message_ECTF_TransactionID                           __CTMsgSym (0x008)
      

/******************************************************************************
 *    Session symbols.
 *****************************************************************************/
#define __CTSessSym(item)              CTsym_Build( CT_objSESSION,\
                                                    CT_vendECTF,\
                                                    (item))

#define Session_ECTF_ServerName                           __CTSessSym ( 0x000 )
#define Session_ECTF_AuthType                             __CTSessSym ( 0x001 )
#define Session_ECTF_AuthToken                            __CTSessSym ( 0x002 )
#define Session_ECTF_UserID                               __CTSessSym ( 0x003 )
#define Session_ECTF_Password                             __CTSessSym ( 0x004 )
#define Session_ECTF_ParmList                             __CTSessSym ( 0x005 )
#define Session_ECTF_ProfileName                          __CTSessSym ( 0x006 )
#define Session_ECTF_StopTransactionID                    __CTSessSym ( 0x007 )
#define Session_ECTF_Create                               __CTSessSym ( 0x008 )
#define Session_ECTF_Destroy                              __CTSessSym ( 0x009 )
#define Session_ECTF_GetParameters                        __CTSessSym ( 0x00A )
#define Session_ECTF_SetParameters                        __CTSessSym ( 0x00B )
#define Session_ECTF_Stop                                 __CTSessSym ( 0x00C )
#define Session_ECTF_LinkDown                             __CTSessSym ( 0x00D )
#define Session_ECTF_Register                             __CTSessSym ( 0x00E )
#define Session_ECTF_FindService                          __CTSessSym ( 0x00F )
#define Session_ECTF_UnregisterService                    __CTSessSym ( 0x010 )
#define Session_ECTF_SendMessage                          __CTSessSym ( 0x011 )
#define Session_ECTF_OSU                                  __CTSessSym ( 0x012 )
#define Session_DLGC_Admin                                __CTSessSym ( 0x017 )
#define Session_ECTF_Group                                __CTSessSym ( 0x018 )
#define Session_ECTF_ReceiveGroup                         __CTSessSym ( 0x019 )
#define Session_DLGC_Address                              __CTSessSym ( 0x01A )
#define Session_DLGC_EmergencyShutdown                    __CTSessSym ( 0x01B )
#define Session_DLGC_NormalShutdown                       __CTSessSym ( 0x01C )
#define Session_ECTF_SourceAddress                        __CTSessSym ( 0x01D )
#define Session_DLGC_DestroySession                       __CTSessSym ( 0x01E )
#define Session_ECTF_ACT                                  __CTSessSym ( 0x01F )

/******************************************************************************
 *    Container symbols.
 *****************************************************************************/
#define __CTContSym( item )            CTsym_Build( CT_objCONTAINER,\
						    CT_vendECTF,\
						    (item) )

#define Container_ECTF_StreamHandle                          __CTContSym(0x000)
#define Container_ECTF_WriteContents                         __CTContSym(0x001)
#define Container_ECTF_AccessMode                            __CTContSym(0x002)
#define Container_ECTF_ChangeMode                            __CTContSym(0x003)
#define Container_ECTF_Flags                                 __CTContSym(0x004)
#define Container_ECTF_Name                                  __CTContSym(0x005)
#define Container_ECTF_CloseObject                           __CTContSym(0x006)
#define Container_ECTF_Options                               __CTContSym(0x007)
#define Container_ECTF_Copy                                  __CTContSym(0x009)
#define Container_ECTF_InputParameters                       __CTContSym(0x00A)
#define Container_ECTF_Create                                __CTContSym(0x00B)
#define Container_ECTF_Destroy                               __CTContSym(0x00D)
#define Container_ECTF_GetObjectList                         __CTContSym(0x00E)
#define Container_ECTF_GetParameters                         __CTContSym(0x00F)
#define Container_ECTF_OpenObject                            __CTContSym(0x010)
#define Container_ECTF_ReadSize                              __CTContSym(0x011)
#define Container_ECTF_Seek                                  __CTContSym(0x012)
#define Container_ECTF_SeekSize                              __CTContSym(0x013)
#define Container_ECTF_Rename                                __CTContSym(0x014)
#define Container_ECTF_Data                                  __CTContSym(0x015)
#define Container_ECTF_MediaInfo                             __CTContSym(0x016)
#define Container_ECTF_WriteSize                             __CTContSym(0x017)
#define Container_ECTF_SetParameters                         __CTContSym(0x018)
#define Container_ECTF_TargetName                            __CTContSym(0x019)
#define Container_ECTF_OutputParameters                      __CTContSym(0x01A)
#define Container_ECTF_InputBuffer                           __CTContSym(0x01B)
#define Container_ECTF_ReadContents                          __CTContSym(0x01C)
#define Container_ECTF_ObjectList                            __CTContSym(0x01D)
#define Container_ECTF_DataStreamHandle                      __CTContSym(0x01E)
#define Container_ECTF_BytesWritten                          __CTContSym(0x01F)
#define Container_ECTF_FileStrategy                          __CTContSym(0x020)
#define Container_ECTF_Created                               __CTContSym(0x021)
#define Container_ECTF_LastChanged                           __CTContSym(0x022)
#define Container_ECTF_FileName                              __CTContSym(0x023)
#define Container_ECTF_Reference                             __CTContSym(0x024)
#define Container_ECTF_Size                                  __CTContSym(0x025)
#define Container_ECTF_Strategy                              __CTContSym(0x026)
#define Container_ECTF_6kADPCM                               __CTContSym(0x027)
#define Container_ECTF_8kADPCM                               __CTContSym(0x028)
#define Container_ECTF_11kADPCM                              __CTContSym(0x029)
#define Container_ECTF_6kMuLawPCM                            __CTContSym(0x02A)
#define Container_ECTF_8kMuLawPCM                            __CTContSym(0x02B)
#define Container_ECTF_11kMuLawPCM                           __CTContSym(0x02C)
#define Container_ECTF_6kALawPCM                             __CTContSym(0x02D)
#define Container_ECTF_8kALawPCM                             __CTContSym(0x02E)
#define Container_ECTF_11kALawPCM                            __CTContSym(0x02F)
#define Container_ECTF_6k8BitLinear                          __CTContSym(0x030)
#define Container_ECTF_8k8BitLinear                          __CTContSym(0x031)
#define Container_ECTF_11k8BitLinear                         __CTContSym(0x032)
#define Container_ECTF_ADSI                                  __CTContSym(0x033)
#define Container_ECTF_TDD                                   __CTContSym(0x034)
#define Container_ECTF_VoiceView                             __CTContSym(0x035)
#define Container_ECTF_EnglishText                           __CTContSym(0x036)
#define Container_ECTF_GermanText                            __CTContSym(0x037)
#define Container_ECTF_SpanishText                           __CTContSym(0x038)
#define Container_ECTF_FrenchText                            __CTContSym(0x039)
#define Container_ECTF_DutchText                             __CTContSym(0x03A)
#define Container_ECTF_KoreanText                            __CTContSym(0x03B)
#define Container_ECTF_AsciiText                             __CTContSym(0x03C)
#define Container_ECTF_Offset                                __CTContSym(0x03D)
#define Container_ECTF_Container                             __CTContSym(0x03E)
#define Container_ECTF_MediaType                             __CTContSym(0x044)
#define Container_ECTF_DefaultMediaType                      __CTContSym(0x045)
#define Container_ECTF_AcceptableMediaTypes                  __CTContSym(0x046)
#define Container_ECTF_CreateObject                          __CTContSym(0x04A)
#define Container_ECTF_Commit                                __CTContSym(0x04B)

/******************************************************************************
 *    Signal Detector symbols.
 *****************************************************************************/
#define __CTSIGDSym(item)              CTsym_Build( CT_objSIGD,\
						    CT_vendECTF,\
                                                    (item))

#define SIGD_ECTF_RetrieveSignals                            __CTSIGDSym(0x000)
#define SIGD_ECTF_FlushBuffer                                __CTSIGDSym(0x001)
#define SIGD_ECTF_NumSignals                                 __CTSIGDSym(0x002)
#define SIGD_ECTF_Patterns                                   __CTSIGDSym(0x003)
#define SIGD_ECTF_OutputBuffer                               __CTSIGDSym(0x004)
#define SIGD_ECTF_SignalBuffer                               __CTSIGDSym(0x005)
#define SIGD_ECTF_ResClass                                   __CTSIGDSym(0x006)
#define SIGD_ECTF_Pattern1                                   __CTSIGDSym(0x008)
#define SIGD_ECTF_Pattern2                                   __CTSIGDSym(0x009)
#define SIGD_ECTF_Pattern3                                   __CTSIGDSym(0x00A)
#define SIGD_ECTF_Pattern4                                   __CTSIGDSym(0x00B)
#define SIGD_ECTF_Pattern5                                   __CTSIGDSym(0x00C)
#define SIGD_ECTF_Pattern6                                   __CTSIGDSym(0x00D)
#define SIGD_ECTF_Pattern7                                   __CTSIGDSym(0x00E)
#define SIGD_ECTF_Pattern8                                   __CTSIGDSym(0x00F)
#define SIGD_ECTF_Pattern9                                   __CTSIGDSym(0x010)
#define SIGD_ECTF_Pattern10                                  __CTSIGDSym(0x011)
#define SIGD_ECTF_Pattern11                                  __CTSIGDSym(0x012)
#define SIGD_ECTF_Pattern12                                  __CTSIGDSym(0x013)
#define SIGD_ECTF_Pattern13                                  __CTSIGDSym(0x014)
#define SIGD_ECTF_Pattern14                                  __CTSIGDSym(0x015)
#define SIGD_ECTF_Pattern15                                  __CTSIGDSym(0x016)
#define SIGD_ECTF_Pattern16                                  __CTSIGDSym(0x017)
#define SIGD_ECTF_DiscardOldest                              __CTSIGDSym(0x018)
#define SIGD_ECTF_BufferSize                                 __CTSIGDSym(0x019)
#define SIGD_ECTF_InitialTimeout                             __CTSIGDSym(0x01A)
#define SIGD_ECTF_IntersigTimeout                            __CTSIGDSym(0x01B)
#define SIGD_ECTF_SignalDetected                             __CTSIGDSym(0x01F)
#define SIGD_ECTF_Stop                                       __CTSIGDSym(0x020)
#define SIGD_ECTF_Mode                                       __CTSIGDSym(0x021)
#define SIGD_ECTF_EnabledEvents                              __CTSIGDSym(0x022)
#define SIGD_ECTF_Buffering                                  __CTSIGDSym(0x023)
#define SIGD_DLGC_Consume                                    __CTSIGDSym(0x024)
#define SIGD_ECTF_PatternCount                               __CTSIGDSym(0x025)
#define SIGD_ECTF_Duration                                   __CTSIGDSym(0x026)
#define SIGD_ECTF_Idle                                       __CTSIGDSym(0x027)
#define SIGD_ECTF_Detecting                                  __CTSIGDSym(0x028)
#define SIGD_DLGC_SignalID                                   __CTSIGDSym(0x02A)
#define SIGD_DLGC_PatternSyntax                              __CTSIGDSym(0x02B)


/******************************************************************************
 *    Group symbols.
 *****************************************************************************/
#define __CTGrpSym(item)            CTsym_Build( CT_objGROUP,\
                                                 CT_vendECTF,\
                                                 (item))

#define Group_ECTF_ACT                                      __CTGrpSym( 0x001 )
#define Group_ECTF_Arrival                                  __CTGrpSym( 0x002 )
#define Group_ECTF_Cause                                    __CTGrpSym( 0x003 )
#define Group_ECTF_Configure                                __CTGrpSym( 0x004 )
#define Group_ECTF_Create                                   __CTGrpSym( 0x005 )
#define Group_ECTF_Destroy                                  __CTGrpSym( 0x006 )
#define Group_ECTF_GetGroupInfo                             __CTGrpSym( 0x007 )
#define Group_ECTF_GetParameterNames                        __CTGrpSym( 0x008 )
#define Group_ECTF_GetParameterRange                        __CTGrpSym( 0x009 )
#define Group_ECTF_GetParameters                            __CTGrpSym( 0x00A )
#define Group_ECTF_GetRTC                                   __CTGrpSym( 0x00B )
#define Group_ECTF_Group                                    __CTGrpSym( 0x00C ) 
#define Group_ECTF_GroupConfig                              __CTGrpSym( 0x00D )
#define Group_ECTF_GroupInfo                                __CTGrpSym( 0x00E )
#define Group_ECTF_GroupSet                                 __CTGrpSym( 0x00F )
#define Group_ECTF_Handoff                                  __CTGrpSym( 0x010 )
#define Group_ECTF_Keys                                     __CTGrpSym( 0x011 )
#define Group_ECTF_KVSet                                    __CTGrpSym( 0x012 )
#define Group_ECTF_NewOwner                                 __CTGrpSym( 0x013 )
#define Group_ECTF_ParameterNames                           __CTGrpSym( 0x014 )
#define Group_ECTF_ParameterRangeSet                        __CTGrpSym( 0x015 )
#define Group_ECTF_Parameters                               __CTGrpSym( 0x016 )
#define Group_ECTF_ParmList                                 __CTGrpSym( 0x017 )
#define Group_ECTF_PutGroupInfo                             __CTGrpSym( 0x018 )
#define Group_ECTF_Retrieve                                 __CTGrpSym( 0x019 )
#define Group_ECTF_Return                                   __CTGrpSym( 0x01A )
#define Group_ECTF_Returned                                 __CTGrpSym( 0x01B )
#define Group_ECTF_RTC                                      __CTGrpSym( 0x01C )
#define Group_ECTF_RTCValidate                              __CTGrpSym( 0x01D )
#define Group_ECTF_SetParameters                            __CTGrpSym( 0x01E )
#define Group_ECTF_SetRTC                                   __CTGrpSym( 0x01F )
#define Group_ECTF_Stop                                     __CTGrpSym( 0x020 )
#define Group_ECTF_Tag                                      __CTGrpSym( 0x021 )
#define Group_ECTF_Timeout                                  __CTGrpSym( 0x022 )
#define Group_ECTF_Unwind                                   __CTGrpSym( 0x023 )
#define Group_ECTF_Session                                  __CTGrpSym( 0x024 )
#define Group_ECTF_DestroyGroups                            __CTGrpSym( 0x027 )
#define Group_ECTF_RTCTrigger                               __CTGrpSym( 0x028 )
#define Group_ECTF_ConditionInfo                            __CTGrpSym( 0x029 )
#define Group_ECTF_WaitEvent                                __CTGrpSym( 0x02A )
#define Group_ECTF_ASI                                      __CTGrpSym( 0x02B )
#define Group_ECTF_Destroyed                                __CTGrpSym( 0x02C )
#define Group_ECTF_Retrieved                                __CTGrpSym( 0x02D )
#define Group_ECTF_ProfileName                              __CTGrpSym( 0x02E )
#define Group_ECTF_HandToMe                                 __CTGrpSym( 0x02F )
#define Group_ECTF_OutputParameters                         __CTGrpSym( 0x030 )
#define Group_ECTF_Command                                  __CTGrpSym( 0x031 )
#define Group_ECTF_TriggerInfo                              __CTGrpSym( 0x032 )
#define Group_ECTF_ResourceName                             __CTGrpSym( 0x033 )
#define Group_ECTF_ArbitrationScheme                        __CTGrpSym( 0x034 )
#define Group_ECTF_FailingRTC                               __CTGrpSym( 0x035 )


/******************************************************************************
 *    Signal Generator Symbols.
 *****************************************************************************/
#define __CTSIGGSym(item)              CTsym_Build( CT_objSIGG,\
                                                    CT_vendECTF,\
                                                    (item))

#define SIGG_ECTF_SendSignals                                __CTSIGGSym(0x000)
#define SIGG_ECTF_SignalList                                 __CTSIGGSym(0x001)
#define SIGG_ECTF_ResClass                                   __CTSIGGSym(0x002)
#define SIGG_ECTF_Stop                                       __CTSIGGSym(0x004)


/******************************************************************************
 *    Player symbols.
 *****************************************************************************/
#define __CTPlayerSym(item)            CTsym_Build( CT_objPLAYER,\
                                                    CT_vendECTF,\
                                                    (item))

#define Player_ECTF_Play                                   __CTPlayerSym(0x000)
#define Player_ECTF_TvmList                                __CTPlayerSym(0x001)
#define Player_ECTF_Offset                                 __CTPlayerSym(0x002)
#define Player_ECTF_ResClass                               __CTPlayerSym(0x003)
#define Player_ECTF_Speed                                  __CTPlayerSym(0x004)
#define Player_ECTF_Volume                                 __CTPlayerSym(0x005)
#define Player_ECTF_Pause                                  __CTPlayerSym(0x006)
#define Player_ECTF_Resume                                 __CTPlayerSym(0x007)
#define Player_ECTF_VolumeChange                           __CTPlayerSym(0x008)
#define Player_ECTF_SpeedChange                            __CTPlayerSym(0x009)
#define Player_ECTF_Marker                                 __CTPlayerSym(0x00A)
#define Player_ECTF_EOD                                    __CTPlayerSym(0x00B)
#define Player_ECTF_Coder                                  __CTPlayerSym(0x00C)
#define Player_ECTF_EnabledEvents                          __CTPlayerSym(0x00D)
#define Player_ECTF_StartPaused                            __CTPlayerSym(0x00E)
#define Player_ECTF_CoderTypes                             __CTPlayerSym(0x00F)
#define Player_ECTF_Duration                               __CTPlayerSym(0x010)
#define Player_ECTF_SpeedUp                                __CTPlayerSym(0x011)
#define Player_ECTF_SpeedDown                              __CTPlayerSym(0x012)
#define Player_ECTF_VolumeUp                               __CTPlayerSym(0x013)
#define Player_ECTF_VolumeDown                             __CTPlayerSym(0x014)
#define Player_ECTF_Stop                                   __CTPlayerSym(0x015)
#define Player_ECTF_ChangeType                             __CTPlayerSym(0x016)
#define Player_ECTF_TVM                                    __CTPlayerSym(0x017)
#define Player_ECTF_ToggleSpeed                            __CTPlayerSym(0x018)
#define Player_ECTF_NormalSpeed                            __CTPlayerSym(0x019)
#define Player_ECTF_ToggleVolume                           __CTPlayerSym(0x01A)
#define Player_ECTF_NormalVolume                           __CTPlayerSym(0x01B)
#define Player_ECTF_JumpForward                            __CTPlayerSym(0x01C)
#define Player_ECTF_JumpBackward                           __CTPlayerSym(0x01D)
#define Player_ECTF_Adjustment                             __CTPlayerSym(0x01E)
#define Player_ECTF_AdjustSpeed                            __CTPlayerSym(0x01F)
#define Player_ECTF_AdjustVolume                           __CTPlayerSym(0x020)
#define Player_ECTF_PlayStarted                            __CTPlayerSym(0x021)
#define Player_ECTF_JumpIncrement                          __CTPlayerSym(0x022)
#define Player_ECTF_Jump                                   __CTPlayerSym(0x023)
#define Player_ECTF_PauseTermination                       __CTPlayerSym(0x024)




/******************************************************************************
 *    Recorder symbols.
 *****************************************************************************/
#define __CTRecorderSym(item)          CTsym_Build( CT_objRECORDER,\
                                                    CT_vendECTF,\
						    (item))

#define Recorder_ECTF_Record                             __CTRecorderSym(0x000)
#define Recorder_ECTF_Tvm                                __CTRecorderSym(0x001)
#define Recorder_ECTF_ResClass                           __CTRecorderSym(0x002)
#define Recorder_ECTF_Pause                              __CTRecorderSym(0x003)
#define Recorder_ECTF_Resume                             __CTRecorderSym(0x004)
#define Recorder_ECTF_Coder                              __CTRecorderSym(0x005)
#define Recorder_ECTF_Stop                               __CTRecorderSym(0x006)
#define Recorder_ECTF_Beep                               __CTRecorderSym(0x007)
#define Recorder_DLGC_FixedBeep                          __CTRecorderSym(0x008)
#define Recorder_ECTF_EnabledEvents                      __CTRecorderSym(0x009)
#define Recorder_ECTF_Duration                           __CTRecorderSym(0x00A)
#define Recorder_ECTF_StartBeep                          __CTRecorderSym(0x00B)
#define Recorder_ECTF_StartPaused                        __CTRecorderSym(0x00C)
#define Recorder_ECTF_CoderTypes                         __CTRecorderSym(0x00D)
#define Recorder_DLGC_Append                             __CTRecorderSym(0x00E)
#define Recorder_DLGC_AGC                                __CTRecorderSym(0x00F)
#define Recorder_ECTF_BeepLength                         __CTRecorderSym(0x010)
#define Recorder_ECTF_BeepFrequency                      __CTRecorderSym(0x011)
#define Recorder_ECTF_PauseCompression                   __CTRecorderSym(0x012)
#define Recorder_ECTF_PauseThreshold                     __CTRecorderSym(0x013)
#define Recorder_ECTF_SilenceTerminationOn               __CTRecorderSym(0x014)
#define Recorder_ECTF_SilenceThreshold                   __CTRecorderSym(0x015)
#define Recorder_ECTF_Silence                            __CTRecorderSym(0x016)
#define Recorder_ECTF_PauseCompressionOn                 __CTRecorderSym(0x017)

/******************************************************************************
 *    EVENT TRIGGER symbols.
 *****************************************************************************/
#define __CTTRISym(item)	CTsym_Build(CT_objTRIGGER,\
					    CT_vendTELSUN,\
					    (item) )
#define Trigger_TELSUN_ChannelHandle		             __CTTRISym(0x001)
#define Trigger_TELSUN_EventType			     __CTTRISym(0x002)
#define Trigger_TELSUN_DataLength			     __CTTRISym(0x003)
#define Trigger_TELSUN_EventData			     __CTTRISym(0x004)
#define Trigger_TELSUN_TermReason 			     __CTTRISym(0x005)

//*************************************************************************
//Public keys
//*************************************************************************
//base value for Switch Control defined keys
#define __CTkvs_PUBLIC(item)  	CTsym_Build( CT_objPUBLIC,\
				             CT_vendTELSUN,\
					     (item) )

//KVSet in messages sent by Switch Control
#define PUBLIC_TELSUN_MessageType                __CTkvs_PUBLIC(0x0000)  
#define PUBLIC_TELSUN_NodeID                     __CTkvs_PUBLIC(0x0001)
#define PUBLIC_TELSUN_SpanID                     __CTkvs_PUBLIC(0x0002)
#define PUBLIC_TELSUN_Channel                    __CTkvs_PUBLIC(0x0003)
#define PUBLIC_TELSUN_OrigSpanID                 __CTkvs_PUBLIC(0x0004)
#define PUBLIC_TELSUN_TermSpanID                 __CTkvs_PUBLIC(0x0005)
#define PUBLIC_TELSUN_OrigChannel                __CTkvs_PUBLIC(0x0006)
#define PUBLIC_TELSUN_TermChannel                __CTkvs_PUBLIC(0x0007)
#define PUBLIC_TELSUN_SpanIDA                    __CTkvs_PUBLIC(0x0008)
#define PUBLIC_TELSUN_ChannelA                   __CTkvs_PUBLIC(0x0009)
#define PUBLIC_TELSUN_SpanIDB                    __CTkvs_PUBLIC(0x000a)
#define PUBLIC_TELSUN_ChannelB                   __CTkvs_PUBLIC(0x000b)
#define PUBLIC_TELSUN_Status                     __CTkvs_PUBLIC(0x000c)
#define PUBLIC_TELSUN_Data                       __CTkvs_PUBLIC(0x000d)
#define PUBLIC_TELSUN_BusyOutAction              __CTkvs_PUBLIC(0x000e)
#define PUBLIC_TELSUN_BusyOutFlag                __CTkvs_PUBLIC(0x000f)
#define PUBLIC_TELSUN_Const                      __CTkvs_PUBLIC(0x0010)
#define PUBLIC_TELSUN_NoLengthData               __CTkvs_PUBLIC(0x0011)
#define PUBLIC_TELSUN_ICBData                    __CTkvs_PUBLIC(0x0012)
#define PUBLIC_SUNTKE_DataWithLength             __CTkvs_PUBLIC(0x0013)
#define PUBLIC_TELSUN_Length                     __CTkvs_PUBLIC(0x0014)
#define PUBLIC_TELSUN_MultiAIB                   __CTkvs_PUBLIC(0x0015)

#define PUBLIC_TELSUN_CallMode                   __CTkvs_PUBLIC(0x0016)
#define PUBLIC_TELSUN_ConnectMode                __CTkvs_PUBLIC(0x0017)
#define PUBLIC_TELSUN_BillFlag                   __CTkvs_PUBLIC(0x0018)
#define PUBLIC_TELSUN_Caller                     __CTkvs_PUBLIC(0x0019)
#define PUBLIC_TELSUN_Called                     __CTkvs_PUBLIC(0x001a)
#define PUBLIC_TELSUN_CallingPartyCategory       __CTkvs_PUBLIC(0x001b)
#define	PUBLIC_TELSUN_StartTime                  __CTkvs_PUBLIC(0x001c)
#define	PUBLIC_TELSUN_EndTime                    __CTkvs_PUBLIC(0x001e)
#define	PUBLIC_TELSUN_NotifyWay                  __CTkvs_PUBLIC(0x001f)
#define	PUBLIC_TELSUN_NotifyCount                __CTkvs_PUBLIC(0x0020)
#define	PUBLIC_TELSUN_NotifyInterval             __CTkvs_PUBLIC(0x0021)
#define	PUBLIC_TELSUN_ScheduleNo                 __CTkvs_PUBLIC(0x0022)
#define	PUBLIC_TELSUN_ScheduleParam              __CTkvs_PUBLIC(0x0023)
#define	PUBLIC_TELSUN_TimerID                    __CTkvs_PUBLIC(0x0024)
#define	PUBLIC_TELSUN_SequenceID                 __CTkvs_PUBLIC(0x0025)
#define	PUBLIC_TELSUN_ErrorMessage               __CTkvs_PUBLIC(0x0026)
#define	PUBLIC_TELSUN_HowToLoadProfile           __CTkvs_PUBLIC(0x0027)
#define	PUBLIC_TELSUN_ProfileName                __CTkvs_PUBLIC(0x0028)

#define PUBLIC_TELSUN_CommonAlertLevel           __CTkvs_PUBLIC(0x0082)
#define PUBLIC_TELSUN_CommonAlertString          __CTkvs_PUBLIC(0x0083)
#define PUBLIC_TELSUN_IP                         __CTkvs_PUBLIC(0x0084)
#define PUBLIC_TELSUN_Port                       __CTkvs_PUBLIC(0x0085)
#define PUBLIC_TELSUN_SenderModule               __CTkvs_PUBLIC(0x0086)
#define PUBLIC_TELSUN_ReceiverModule             __CTkvs_PUBLIC(0x0087)
#define PUBLIC_TELSUN_TotalAdjacentAddress  	 __CTkvs_PUBLIC(0x0088)
#define PUBLIC_TELSUN_LeavingsNumber			 __CTkvs_PUBLIC(0x0089)
#define PUBLIC_TELSUN_ConfigData				 __CTkvs_PUBLIC(0x008a)
#define PUBLIC_TELSUN_StationNo                  __CTkvs_PUBLIC(0x008b)
#define PUBLIC_TELSUN_Entity                     __CTkvs_PUBLIC(0x008c)
#define PUBLIC_TELSUN_Severity                   __CTkvs_PUBLIC(0x008d)
#define PUBLIC_TELSUN_AlarmNumber                __CTkvs_PUBLIC(0x008e)
#define PUBLIC_TELSUN_AlarmData                  __CTkvs_PUBLIC(0x008f)

//*************************************************************************
//Private keys of SCR
//**************************************************************************
//base value for SCR defined keys
#define __CTkvs_SCR(item)  CTsym_Build(CT_objSCR,CT_vendTELSUN, (item))

#define SCR_TELSUN_StationNo                   __CTkvs_SCR(1)
#define SCR_TELSUN_ASIName                     __CTkvs_SCR(2)
#define SCR_TELSUN_TotalIncoming	       __CTkvs_SCR(3)
#define SCR_TELSUN_ValidServer		       __CTkvs_SCR(4)
#define SCR_TELSUN_StartTime 		       __CTkvs_SCR(5)
#define SCR_TELSUN_Command		       __CTkvs_SCR(6)
#define SCR_TELSUN_TraceFileName	       __CTkvs_SCR(7)
#define SCR_TELSUN_TraceValue		       __CTkvs_SCR(8)
#define SCR_TELSUN_TraceStatus		       __CTkvs_SCR(9)
#define SCR_TELSUN_TotalSession		       __CTkvs_SCR(10)
#define SCR_TELSUN_IdleSession		       __CTkvs_SCR(11)
#define SCR_TELSUN_CalloutTimes		       __CTkvs_SCR(12)
#define SCR_TELSUN_CalloutSuccTimes	       __CTkvs_SCR(13)
#define SCR_TELSUN_InValidServer	       __CTkvs_SCR(14)
#define SCR_TELSUN_ErrorReason		       __CTkvs_SCR(15)
//*************************************************************************
//Private keys of SWITCH
//**************************************************************************
#define __CTkvs_SWITCH(item)  CTsym_Build(CT_objSWITCH,CT_vendTELSUN,(item))

#define SWITCH_TELSUN_ConferenceID               __CTkvs_SWITCH(0x0004)
#define SWITCH_TELSUN_ConferenceType             __CTkvs_SWITCH(0x0005)
#define SWITCH_TELSUN_CallProcessingEvent        __CTkvs_SWITCH(0x0006)
#define SWITCH_TELSUN_ReleaseDataType            __CTkvs_SWITCH(0x0007)
//Collect Digit String --- Cds
#define SWITCH_TELSUN_CdsMode                    __CTkvs_SWITCH(0x0008)
#define SWITCH_TELSUN_CdsMaxDigits               __CTkvs_SWITCH(0x0009)
#define SWITCH_TELSUN_CdsNumTermCharactors       __CTkvs_SWITCH(0x000a)
#define SWITCH_TELSUN_CdsConfigBytes             __CTkvs_SWITCH(0x000b)
#define SWITCH_TELSUN_CdsTermCharactors          __CTkvs_SWITCH(0x000c)
#define SWITCH_TELSUN_CdsInterdigitTimer         __CTkvs_SWITCH(0x000d)
#define SWITCH_TELSUN_CdsFirstDigitTimer         __CTkvs_SWITCH(0x000e)
#define SWITCH_TELSUN_CdsCompletionTimer         __CTkvs_SWITCH(0x000f)
#define SWITCH_TELSUN_CdsMinRecvDigitDurationTimer  __CTkvs_SWITCH(0x0010)
#define SWITCH_TELSUN_CdsAddrSignalingType       __CTkvs_SWITCH(0x0011)
#define SWITCH_TELSUN_CdsNumDigitStrings         __CTkvs_SWITCH(0x0012)
#define SWITCH_TELSUN_CdsResuDigitCollectTimer   __CTkvs_SWITCH(0x0013)

#define SWITCH_TELSUN_ConferenceSize             __CTkvs_SWITCH(0x0014)
#define SWITCH_TELSUN_BroadcastEnable            __CTkvs_SWITCH(0x0015)
#define SWITCH_TELSUN_TransmitCallProgressPatternID __CTkvs_SWITCH(0x0016)
#define SWITCH_TELSUN_NumCyclesToTransmit        __CTkvs_SWITCH(0x0017)
#define SWITCH_TELSUN_GenerateEventFlag          __CTkvs_SWITCH(0x0018)
#define SWITCH_TELSUN_ConnectDataType            __CTkvs_SWITCH(0x0019)
#define SWITCH_TELSUN_ChannelAPadValue           __CTkvs_SWITCH(0x001a)
#define SWITCH_TELSUN_ChannelBPadValue           __CTkvs_SWITCH(0x001b)
#define SWITCH_TELSUN_CpcDetectionAction         __CTkvs_SWITCH(0x001c)
#define SWITCH_TELSUN_ChannelAEncodingFormat     __CTkvs_SWITCH(0x001d)
#define SWITCH_TELSUN_ChannelBEncodingFormat     __CTkvs_SWITCH(0x001e)
#define SWITCH_TELSUN_ServiceType                __CTkvs_SWITCH(0x001f)
#define SWITCH_TELSUN_StringCount                __CTkvs_SWITCH(0x0020)
#define SWITCH_TELSUN_StringMode                 __CTkvs_SWITCH(0x0021)
#define SWITCH_TELSUN_FirstDigitDuration         __CTkvs_SWITCH(0x0022)
#define SWITCH_TELSUN_DigitDuration              __CTkvs_SWITCH(0x0023)
#define SWITCH_TELSUN_InterdigitDuration         __CTkvs_SWITCH(0x0024)
#define SWITCH_TELSUN_DelayDuration              __CTkvs_SWITCH(0x0025)
#define SWITCH_TELSUN_String1DigitCount          __CTkvs_SWITCH(0x0026)
#define SWITCH_TELSUN_String1Digits              __CTkvs_SWITCH(0x0027)
#define SWITCH_TELSUN_String2DigitCount          __CTkvs_SWITCH(0x0028)
#define SWITCH_TELSUN_String2Digits              __CTkvs_SWITCH(0x0029)
#define SWITCH_TELSUN_PPLComponentID             __CTkvs_SWITCH(0x002a)
#define SWITCH_TELSUN_PPLEvent                   __CTkvs_SWITCH(0x002b)
#define SWITCH_TELSUN_ConfigFlag                 __CTkvs_SWITCH(0x002c)
#define SWITCH_TELSUN_EventFlag                  __CTkvs_SWITCH(0x002d)
#define SWITCH_TELSUN_AnnouncementCount          __CTkvs_SWITCH(0x002e)

#define SWITCH_TELSUN_SpanService        	 __CTkvs_SWITCH(0x002f)
#define SWITCH_TELSUN_ChannelService             __CTkvs_SWITCH(0x0030)

#define SWITCH_TELSUN_Channels   	 	 __CTkvs_SWITCH(0x0032)
#define SWITCH_TELSUN_EventID                    __CTkvs_SWITCH(0x0033)

//************************************************************************
//Private keys of COMM
//************************************************************************

//KVset in meggages from COMMUNICATIONS module

#define __CTkvs_COMM(item)	 CTsym_Build( CT_objCOMMCTRL, CT_vendTELSUN, (item) )

#define COMM_TELSUN_ConferenceID              __CTkvs_COMM(0x0000)
#define COMM_TELSUN_CallProcessingEvent       __CTkvs_COMM(0x0001)
#define COMM_TELSUN_ReleaseDataType           __CTkvs_COMM(0x0002)

// Call Processing Analysis --- Cpa
#define COMM_TELSUN_CpaResult		      __CTkvs_COMM(0x0003)
#define COMM_TELSUN_ChannelStatus             __CTkvs_COMM(0x0004)
#define COMM_TELSUN_PurgeReason               __CTkvs_COMM(0x0005)
#define COMM_TELSUN_StackID                   __CTkvs_COMM(0x0006)
#define COMM_TELSUN_LinkID                    __CTkvs_COMM(0x0007)
#define COMM_TELSUN_PPLComponentID            __CTkvs_COMM(0x0008)
#define COMM_TELSUN_PPLEvent                  __CTkvs_COMM(0x0009)
#define COMM_TELSUN_ResendFlag                __CTkvs_COMM(0x000a)
#define COMM_TELSUN_AddrDataType              __CTkvs_COMM(0x000b)

#define COMM_TELSUN_Slot				__CTkvs_COMM(0x000c)
#define COMM_TELSUN_PhysicalSpan		__CTkvs_COMM(0x000d)
#define COMM_TELSUN_NodeEntity          __CTkvs_COMM(0x000e)
#define COMM_TELSUN_DataLength          __CTkvs_COMM(0x000f)

#define COMM_TELSUN_SystemType			__CTkvs_COMM(0x0011)
#define COMM_TELSUN_EXCPUID				__CTkvs_COMM(0x0012)
#define COMM_TELSUN_EXCPUState			__CTkvs_COMM(0x0013)
#define COMM_TELSUN_AdjacentEXCPUState	__CTkvs_COMM(0x0014)
#define COMM_TELSUN_StatusBits			__CTkvs_COMM(0x0015)
#define COMM_TELSUN_Reserved			__CTkvs_COMM(0x0016)
#define COMM_TELSUN_Severity			__CTkvs_COMM(0x0017)
#define COMM_TELSUN_Entity				__CTkvs_COMM(0x0018)
#define COMM_TELSUN_AlarmNumber			__CTkvs_COMM(0x0019)

#define C0MM_TELSUN_SlotNumber			__CTkvs_COMM(0x001b)
#define C0MM_TELSUN_PhysicalNodeID		__CTkvs_COMM(0x001c)
#define C0MM_TELSUN_NewNodeID			__CTkvs_COMM(0x001d)
#define COMM_TELSUN_SIMMNumber			__CTkvs_COMM(0x001e)
#define C0MM_TELSUN_DestinationID		__CTkvs_COMM(0x001f)
#define COMM_TELSUN_RouteID				__CTkvs_COMM(0x0020)
#define COMM_TELSUN_SlotofPrimaryCard	__CTkvs_COMM(0x0021)
#define COMM_TELSUN_SlotofSecondaryCard __CTkvs_COMM(0x0022)
#define COMM_TELSUN_SlotofActiveCard	__CTkvs_COMM(0x0023)
#define COMM_TELSUN_AnnounceCount		__CTkvs_COMM(0x0024)



//***********************************************************************
//Private keys of MAINT
//***********************************************************************
#define __CTkvs_MAINT(item)  CTsym_Build(CT_objMAINT,CT_vendTELSUN, (item) )

#define MAINT_TELSUN_LogicalNodeID   __CTkvs_MAINT(0x0001)

#define MAINT_TELSUN_AnswerSupervisionMode  __CTkvs_MAINT(0x0006)
//Assign EXS Host/Slave
#define MAINT_TELSUN_HostID          __CTkvs_MAINT(0x0007)
#define MAINT_TELSUN_SlaveID         __CTkvs_MAINT(0x0008)
//Assign logical node ID
#define MAINT_TELSUN_PhysicalNodeID  __CTkvs_MAINT(0x0009)
//Asign logical span ID
#define MAINT_TELSUN_LogicalSpanID   __CTkvs_MAINT(0x000a)
#define MAINT_TELSUN_SlotNumber      __CTkvs_MAINT(0x000b)
#define MAINT_TELSUN_PhysicalSpan    __CTkvs_MAINT(0x000c)
//B channel configure
#define MAINT_TELSUN_Entity          __CTkvs_MAINT(0x000d)
#define MAINT_TELSUN_Value           __CTkvs_MAINT(0x000e)
//Busy out flag configure
#define MAINT_TELSUN_BusyOutFlag     __CTkvs_MAINT(0x000f)
//Call progress analysis class configure
#define MAINT_TELSUN_UpdateAllFlag   __CTkvs_MAINT(0x0010)
#define MAINT_TELSUN_ClassID         __CTkvs_MAINT(0x0011)
#define MAINT_TELSUN_Action          __CTMAINTCmdsym(0x0012)
//Call progress analysis pattern configure
#define CmdNAINT_TELSUN_PatternID       __CTkvs_MAINT(0x0014)
//CCS redundancy configure
#define MAINT_TELSUN_PrimaryCardSlot __CTkvs_MAINT(0x0015)
#define MAINT_TELSUN_SecondCardSlot  __CTkvs_MAINT(0x0016)
#define MAINT_TELSUN_RedundancyType  __CTkvs_MAINT(0x0017)
//D channel assign
#define MAINT_TELSUN_AddressType     __CTkvs_MAINT(0x0018)
#define MAINT_TELSUN_SecondFacility  __CTkvs_MAINT(0x0019)

#define MAINT_TELSUN_PrimarySpanID   __CTkvs_MAINT(0x001b)
#define MAINT_TELSUN_PrimaryChannel  __CTkvs_MAINT(0x001c)
#define MAINT_TELSUN_SecondSpanID    __CTkvs_MAINT(0x001d)
#define MAINT_TELSUN_SecondChannel   __CTkvs_MAINT(0x001e)
//Distant end release mode configure
#define MAINT_TELSUN_DistantReleaseMode __CTkvs_MAINT(0x001f)
//DSP SIMM configure
#define MAINT_TELSUN_SIMMNumber      __CTkvs_MAINT(0x0020)
#define MAINT_TELSUN_FuncTypeDSP0    __CTkvs_MAINT(0x0021)
#define MAINT_TELSUN_FuncTypeDSP1    __CTkvs_MAINT(0x0022)
#define MAINT_TELSUN_FuncTypeDSP2    __CTkvs_MAINT(0x0023)
#define MAINT_TELSUN_FuncTypeDSP3    __CTkvs_MAINT(0x0024)
//E1 span configure
#define MAINT_TELSUN_Format          __CTkvs_MAINT(0x0025)
#define MAINT_TELSUN_LineLength      __CTkvs_MAINT(0x0026)
#define MAINT_TELSUN_SARegisters     __CTkvs_MAINT(0x0027)
#define MAINT_TELSUN_TS16Register    __CTkvs_MAINT(0x0028)
//Filter/Timer configure
#define MAINT_TELSUN_FilterTimerType __CTkvs_MAINT(0x0029)
#define MAINT_TELSUN_FilterTimerID   __CTkvs_MAINT(0x002a)
//Flash timing configure
#define MAINT_TELSUN_FlashMode       __CTkvs_MAINT(0x002b)
//Inpulsing parameters configure
#define MAINT_TELSUN_StageNumber     __CTkvs_MAINT(0x002c)
#define MAINT_TELSUN_DigStrNum       __CTkvs_MAINT(0x002d)
#define MAINT_TELSUN_StageComTimeOut __CTkvs_MAINT(0x002e)
#define MAINT_TELSUN_AddressSignType __CTkvs_MAINT(0x002f)
#define MAINT_TELSUN_CollMethod1     __CTkvs_MAINT(0x0030)
#define MAINT_TELSUN_CollData1       __CTkvs_MAINT(0x0031)
#define MAINT_TELSUN_CollMethod2     __CTkvs_MAINT(0x0032)
#define MAINT_TELSUN_CollData2       __CTkvs_MAINT(0x0033)
//Inseize instruction list configure
#define MAINT_TELSUN_InstructNumber  __CTkvs_MAINT(0x0034)
#define MAINT_TELSUN_InstructType    __CTkvs_MAINT(0x0035)
//Local end release mode configure
#define MAINT_TELSUN_LocalReleaseMode __CTkvs_MAINT(0x0036)
//Loop timing configure
#define MAINT_TELSUN_LoopTimingType  __CTkvs_MAINT(0x0037)
//Poll interval configure
#define MAINT_TELSUN_PollInterval    __CTkvs_MAINT(0x0038)
//PPL asign
#define MAINT_TELSUN_PPLComponent    __CTkvs_MAINT(0x0039)
#define MAINT_TELSUN_ProtocolID      __CTkvs_MAINT(0x003a)
//PPL audit configure
#define MAINT_TELSUN_AuditType       __CTkvs_MAINT(0x003b)
//PPL configure
#define MAINT_TELSUN_PPLEntity       __CTkvs_MAINT(0x003c)
//PPL create
#define MAINT_TELSUN_PPLProtocolName __CTkvs_MAINT(0x003d)
//PPL delete
#define MAINT_TELSUN_PPLEntityID     __CTkvs_MAINT(0x003e)
//PPL table download
#define MAINT_TELSUN_TableType       __CTkvs_MAINT(0x003f)
#define MAINT_TELSUN_TableID         __CTkvs_MAINT(0x0040)
//PPL timer configure
#define MAINT_TELSUN_PPLTimerType    __CTkvs_MAINT(0x0041)
#define MAINT_TELSUN_PPLTimerID      __CTkvs_MAINT(0x0042)
#define MAINT_TELSUN_TimerValue      __CTkvs_MAINT(0x0043)
//PPL transmit signal configure
#define MAINT_TELSUN_ProtocolSignalingState  __CTkvs_MAINT(0x0044)
#define CmdMAINT_TELSUN_SignalingBits   __CTkvs_MAINT(0x0045)
//Receive signaling configure
#define MAINT_TELSUN_SignalingType   __CTkvs_MAINT(0x0046)
#define MAINT_TELSUN_SignalingValue  __CTkvs_MAINT(0x0047)
#define MAINT_TELSUN_TransmissionMode  __CTkvs_MAINT(0x0048)
#define MAINT_TELSUN_BitMask         __CTkvs_MAINT(0x0049)
//Recorded announcement delete
#define MAINT_TELSUN_ForceFlag       __CTkvs_MAINT(0x004a)
//Recorded announcement download
#define MAINT_TELSUN_AnnounID        __CTkvs_MAINT(0x004b)
//Recorded announcement download initiate
#define MAINT_TELSUN_AnnounSize      __CTkvs_MAINT(0x004c)
#define MAINT_TELSUN_AnnounChecksum  __CTkvs_MAINT(0x004d)
#define MAINT_TELSUN_AnnounFormat    __CTkvs_MAINT(0x004e)
#define MAINT_TELSUN_EncodingFormat  __CTkvs_MAINT(0x004f)
//Server state configure
#define MAINT_TELSUN_LogicalRingID   __CTkvs_MAINT(0x0050)
//SS7 CIC configure
#define MAINT_TELSUN_DPC             __CTkvs_MAINT(0x0051)
//SS7 ISUP message format configure
#define MAINT_TELSUN_StackID         __CTkvs_MAINT(0x0052)
//SS7 signaling link donfigure
#define MAINT_TELSUN_SignalingLinkCode  __CTkvs_MAINT(0x0053)
#define MAINT_TELSUN_DataRate           __CTkvs_MAINT(0x0054)
#define MAINT_TELSUN_LinkSetID          __CTkvs_MAINT(0x0055)
#define MAINT_TELSUN_LinkID             __CTkvs_MAINT(0x0056)
//SS7 signaling link set configure
#define MAINT_TELSUN_APC                __CTkvs_MAINT(0x0057)
//SS7 signaling route configure
#define MAINT_TELSUN_DestinationID      __CTkvs_MAINT(0x0058)
#define MAINT_TELSUN_RouteID            __CTkvs_MAINT(0x0059)
#define MAINT_TELSUN_Priority           __CTkvs_MAINT(0x005a)
//Standby lien card configure
#define MAINT_TELSUN_CardType           __CTkvs_MAINT(0x005b)
//Start dial configure
#define MAINT_TELSUN_StartDialType      __CTkvs_MAINT(0x005c)
#define MAINT_TELSUN_StartDialValue     __CTkvs_MAINT(0x005d)
//Synchromization priority list configure
#define MAINT_TELSUN_PriSynMode1        __CTkvs_MAINT(0x005e)
#define MAINT_TELSUN_PriSynMode2        __CTkvs_MAINT(0x005f)
#define MAINT_TELSUN_PriSynMode3        __CTkvs_MAINT(0x0060)
#define MAINT_TELSUN_PriSynMode4        __CTkvs_MAINT(0x0061)
#define MAINT_TELSUN_PriSynMode5        __CTkvs_MAINT(0x0062)
//Tag configure
#define MAINT_TELSUN_Tag                __CTkvs_MAINT(0x0063)
//Time set
#define MAINT_TELSUN_Month              __CTkvs_MAINT(0x0064)
#define MAINT_TELSUN_Day                __CTkvs_MAINT(0x0065)
#define MAINT_TELSUN_Year               __CTkvs_MAINT(0x0066)
#define MAINT_TELSUN_Hour               __CTkvs_MAINT(0x0067)
#define MAINT_TELSUN_Minute             __CTkvs_MAINT(0x0068)
#define MAINT_TELSUN_Second             __CTkvs_MAINT(0x0069)
//Transmit tone configure
#define MAINT_TELSUN_ToneType           __CTkvs_MAINT(0x006a)

#define MAINT_TELSUN_Flag                  __CTkvs_MAINT(0x0072)
#define MAINT_TELSUN_ChaBPadVal            __CTkvs_MAINT(0x0073)
#define MAINT_TELSUN_ConferenceID          __CTkvs_MAINT(0x0076)
#define MAINT_TELSUN_ServiceType           __CTkvs_MAINT(0x0077)
#define MAINT_TELSUN_ConfigType            __CTkvs_MAINT(0x0078)
#define MAINT_TELSUN_AnnouncementID        __CTkvs_MAINT(0x0079)

#define MAINT_TELSUN_Slot				   __CTkvs_MAINT(0x007a)
#define MAINT_TELSUN_NewNodeID			   __CTkvs_MAINT(0x007b)
#define MAINT_TELSUN_BaseCICNumber		   __CTkvs_MAINT(0x007c)
#define MAINT_TELSUN_BaseCICSpan		   __CTkvs_MAINT(0X007d)
#define MAINT_TELSUN_BaseChanel			   __CTkvs_MAINT(0x007e)
#define MAINT_TELSUN_GroupCIINumber		   __CTkvs_MAINT(0x007f)	


#define MAINT_TELSUN_CommandCode			__CTkvs_MAINT(0x00A0)
#define MAINT_TELSUN_InputInt1				__CTkvs_MAINT(0x00A1)
#define MAINT_TELSUN_InputInt2				__CTkvs_MAINT(0x00A2)
#define	MAINT_TELSUN_InputString1			__CTkvs_MAINT(0x00A3)
#define MAINT_TELSUN_InputString2			__CTkvs_MAINT(0x00A4)
	
#define MAINT_TELSUN_ResultStatus			__CTkvs_MAINT(0x00A7)
#define MAINT_TELSUN_ResultString			__CTkvs_MAINT(0x00A8)
#define MAINT_TELSUN_ResultStringArray		__CTkvs_MAINT(0x00A9)

//
//*********************************************************************
//Private keys of CONFIG
//**********************************************************************

#define __CTkvs_CONFIG(item) CTsym_Build(CT_objCONFIG,\
					    CT_vendTELSUN,\
					    (item) )
#define CONFIG_TELSUN_BootLoaderMaRev     __CTkvs_CONFIG(0x00a3)
#define CONFIG_TELSUN_BootLoaderMiRev     __CTkvs_CONFIG(0x00a4)
#define CONFIG_TELSUN_SysSoftMaRev        __CTkvs_CONFIG(0x00a5)
#define CONFIG_TELSUN_SysSoftMiRev        __CTkvs_CONFIG(0x00a6)
#define CONFIG_TELSUN_SysSoftBDNum        __CTkvs_CONFIG(0x00a7)
#define CONFIG_TELSUN_EX_CPUTimestamp     __CTkvs_CONFIG(0x00a8)
#define CONFIG_TELSUN_AdjEX_CPUTimestamp  __CTkvs_CONFIG(0x00a9)


#define CONFIG_TELSUN_SocketNumber        __CTkvs_CONFIG(0x0001)
//Length of Ip address Number
#define CONFIG_TELSUN_IPNumber            __CTkvs_CONFIG(0x0002)
//Ip address Number pointer (string)
#define CONFIG_TELSUN_LogicalNodeId       __CTkvs_CONFIG(0x0003)
#define CONFIG_TELSUN_LogicSpanID         __CTkvs_CONFIG(0x0004)
#define CONFIG_TELSUN_SlotNumber          __CTkvs_CONFIG(0x0005)
#define CONFIG_TELSUN_PhysicalSpan        __CTkvs_CONFIG(0x0006)
#define CONFIG_TELSUN_Status              __CTkvs_CONFIG(0x0007)
#define CONFIG_TELSUN_AnswerMode          __CTkvs_CONFIG(0x000c)
#define CONFIG_TELSUN_HostLogicId         __CTkvs_CONFIG(0x000d)
#define CONFIG_TELSUN_SlaveLogicId        __CTkvs_CONFIG(0x000e)
#define CONFIG_TELSUN_PhysicalNode        __CTkvs_CONFIG(0x000f)
#define CONFIG_SINTEK_NewNode             __CTkvs_CONFIG(0x0010)
#define CONFIG_TELSUN_Flag                __CTkvs_CONFIG(0x0011)
#define CONFIG_TELSUN_UpdateFlag          __CTkvs_CONFIG(0x0012)
#define CONFIG_TELSUN_ClassId             __CTkvs_CONFIG(0x0013)
#define CONFIG_TELSUN_Action              __CTkvs_CONFIG(0x0014)
#define CONFIG_TELSUN_PatternId           __CTkvs_CONFIG(0x0015)
#define CONFIG_TELSUN_Data                __CTkvs_CONFIG(0x0016)
#define CONFIG_TELSUN_SlotPrim            __CTkvs_CONFIG(0x0017)
#define CONFIG_TELSUN_SlotSecond          __CTkvs_CONFIG(0x0018)
#define CONFIG_TELSUN_PrimSlot            __CTkvs_CONFIG(0x0019)
#define CONFIG_TELSUN_SecondSlot          __CTkvs_CONFIG(0x001a)
#define CONFIG_TELSUN_RedunType           __CTkvs_CONFIG(0x001b)
#define CONFIG_TELSUN_ReleaseMode         __CTkvs_CONFIG(0x001c)
#define CONFIG_TELSUN_BReNum              __CTkvs_CONFIG(0x001d)
#define CONFIG_TELSUN_BRecord             __CTkvs_CONFIG(0x001e)
#define CONFIG_TELSUN_TimeStamp           __CTkvs_CONFIG(0x001f)
#define CONFIG_TELSUN_SReNum              __CTkvs_CONFIG(0x0020)
#define CONFIG_TELSUN_SRecord             __CTkvs_CONFIG(0x0021)
#define CONFIG_TELSUN_DspSlot             __CTkvs_CONFIG(0x0022)
#define CONFIG_TELSUN_SimmNum             __CTkvs_CONFIG(0x0023)
#define CONFIG_TELSUN_Dsp0                __CTkvs_CONFIG(0x0024)
#define CONFIG_TELSUN_Dsp1                __CTkvs_CONFIG(0x0025)
#define CONFIG_TELSUN_Dsp2                __CTkvs_CONFIG(0x0026)
#define CONFIG_TELSUN_Dsp3                __CTkvs_CONFIG(0x0027)
#define CONFIG_TELSUN_Format              __CTkvs_CONFIG(0x0028)
#define CONFIG_TELSUN_LineLen             __CTkvs_CONFIG(0x0029)
#define CONFIG_TELSUN_SARegi              __CTkvs_CONFIG(0x002a)
#define CONFIG_TELSUN_Ts16Regi            __CTkvs_CONFIG(0x002b)
#define CONFIG_TELSUN_LogicRing           __CTkvs_CONFIG(0x002c)
#define CONFIG_TELSUN_Entity              __CTkvs_CONFIG(0x002d)
#define CONFIG_TELSUN_RingData            __CTkvs_CONFIG(0x002e)
#define CONFIG_TELSUN_EntityTime          __CTkvs_CONFIG(0x002f)
#define CONFIG_TELSUN_DataTime            __CTkvs_CONFIG(0x0030)
#define CONFIG_TELSUN_NodeEntity          __CTkvs_CONFIG(0x0031)
#define CONFIG_TELSUN_DataLength          __CTkvs_CONFIG(0x0032)
#define CONFIG_TELSUN_NodeData            __CTkvs_CONFIG(0x0033)
#define CONFIG_TELSUN_FilterType          __CTkvs_CONFIG(0x0034)
#define CONFIG_TELSUN_FilterId            __CTkvs_CONFIG(0x0035)
#define CONFIG_TELSUN_Value               __CTkvs_CONFIG(0x0036)
#define CONFIG_TELSUN_StageNum            __CTkvs_CONFIG(0x0037)
#define CONFIG_TELSUN_DigNum              __CTkvs_CONFIG(0x0038)
#define CONFIG_TELSUN_StageComp           __CTkvs_CONFIG(0x0039)
#define CONFIG_TELSUN_AddrSign            __CTkvs_CONFIG(0x003a)
#define CONFIG_TELSUN_CollMeth1           __CTkvs_CONFIG(0x003b)
#define CONFIG_TELSUN_CollData1           __CTkvs_CONFIG(0x003c)
#define CONFIG_TELSUN_CollMeth2           __CTkvs_CONFIG(0x003d)
#define CONFIG_TELSUN_CollData2           __CTkvs_CONFIG(0x003e)
#define CONFIG_TELSUN_InstrNum            __CTkvs_CONFIG(0x003f)
#define CONFIG_TELSUN_InstrType           __CTkvs_CONFIG(0x0040)
#define CONFIG_TELSUN_Data0               __CTkvs_CONFIG(0x0041)
#define CONFIG_TELSUN_Data1               __CTkvs_CONFIG(0x0042)
#define CONFIG_TELSUN_RealMode            __CTkvs_CONFIG(0x0043)
#define CONFIG_TELSUN_LoopSlot            __CTkvs_CONFIG(0x0044)
#define CONFIG_TELSUN_LoopType            __CTkvs_CONFIG(0x0045)
#define CONFIG_TELSUN_EncodeFormat        __CTkvs_CONFIG(0x0046)
#define CONFIG_TELSUN_PollInterv          __CTkvs_CONFIG(0x0047)
#define CONFIG_TELSUN_CompoId             __CTkvs_CONFIG(0x0048)
#define CONFIG_TELSUN_ProtoId             __CTkvs_CONFIG(0x0049)
#define CONFIG_TELSUN_PplSlot             __CTkvs_CONFIG(0x004a)
#define CONFIG_TELSUN_AuditType           __CTkvs_CONFIG(0x004b)
#define CONFIG_TELSUN_PplEntity           __CTkvs_CONFIG(0x004c)
#define CONFIG_TELSUN_ConfiData           __CTkvs_CONFIG(0x004d)
#define CONFIG_TELSUN_NumLocat            __CTkvs_CONFIG(0x004e)
#define CONFIG_TELSUN_LocatData           __CTkvs_CONFIG(0x004f)
#define CONFIG_TELSUN_ProtoName           __CTkvs_CONFIG(0x0050)
#define CONFIG_TELSUN_TabNum              __CTkvs_CONFIG(0x0051)
#define CONFIG_TELSUN_TabData             __CTkvs_CONFIG(0x0052)
#define CONFIG_TELSUN_TableType           __CTkvs_CONFIG(0x0053)
#define CONFIG_TELSUN_TableId             __CTkvs_CONFIG(0x0054)
#define CONFIG_TELSUN_DataTable           __CTkvs_CONFIG(0x0055)
#define CONFIG_TELSUN_ErrorLength         __CTkvs_CONFIG(0x0056)
#define CONFIG_TELSUN_ErrorType           __CTkvs_CONFIG(0x0057)
#define CONFIG_TELSUN_ErrorData           __CTkvs_CONFIG(0x0058)
#define CONFIG_TELSUN_TableSize           __CTkvs_CONFIG(0x0059)
#define CONFIG_TELSUN_TableName           __CTkvs_CONFIG(0x005a)
#define CONFIG_TELSUN_PplLogicSpan        __CTkvs_CONFIG(0x005b)
#define CONFIG_TELSUN_PplChannel          __CTkvs_CONFIG(0x005c)
#define CONFIG_TELSUN_PplTimerType        __CTkvs_CONFIG(0x005d)
#define CONFIG_TELSUN_PplTimerId          __CTkvs_CONFIG(0x005e)
#define CONFIG_TELSUN_PplTimerValue       __CTkvs_CONFIG(0x005f)
#define CONFIG_TELSUN_SignalingState      __CTkvs_CONFIG(0x0060)
#define CONFIG_TELSUN_SignalingBits       __CTkvs_CONFIG(0x0061)
#define CONFIG_TELSUN_SignalingType       __CTkvs_CONFIG(0x0062)
#define CONFIG_TELSUN_SignalingValue      __CTkvs_CONFIG(0x0063)
#define CONFIG_TELSUN_SignalingMode       __CTkvs_CONFIG(0x0064)
#define CONFIG_TELSUN_BitMask             __CTkvs_CONFIG(0x0065)
#define CONFIG_TELSUN_ForceFlag           __CTkvs_CONFIG(0x0066)
#define CONFIG_TELSUN_AnnoId              __CTkvs_CONFIG(0x0067)
#define CONFIG_TELSUN_AnnoData            __CTkvs_CONFIG(0x0068)
#define CONFIG_TELSUN_AnnoSize            __CTkvs_CONFIG(0x0069)
#define CONFIG_TELSUN_AnnoChecksum        __CTkvs_CONFIG(0x006a)
#define CONFIG_TELSUN_AnnoFormat          __CTkvs_CONFIG(0x006b)
#define CONFIG_TELSUN_AnnoEncod           __CTkvs_CONFIG(0x006c)
#define CONFIG_TELSUN_LogicRingNum        __CTkvs_CONFIG(0x006d)
#define CONFIG_TELSUN_FilterEnti          __CTkvs_CONFIG(0x006e)
#define CONFIG_TELSUN_FilterValue         __CTkvs_CONFIG(0x006f)
#define CONFIG_TELSUN_StackId             __CTkvs_CONFIG(0x0070)
#define CONFIG_TELSUN_CICNum              __CTkvs_CONFIG(0x0071)
#define CONFIG_TELSUN_CICSpan             __CTkvs_CONFIG(0x0072)
#define CONFIG_TELSUN_CICChann            __CTkvs_CONFIG(0x0073)
#define CONFIG_TELSUN_CICGroup            __CTkvs_CONFIG(0x0074)
#define CONFIG_TELSUN_DPC                 __CTkvs_CONFIG(0x0075)
#define CONFIG_TELSUN_IsupMsgIn           __CTkvs_CONFIG(0x0076)
#define CONFIG_TELSUN_IsupMsgId           __CTkvs_CONFIG(0x0077)
#define CONFIG_TELSUN_IsupPrior           __CTkvs_CONFIG(0x0078)
#define CONFIG_TELSUN_MsgLen              __CTkvs_CONFIG(0x0079)
#define CONFIG_TELSUN_IsupData            __CTkvs_CONFIG(0x007a)
#define CONFIG_TELSUN_S7LogicSpan         __CTkvs_CONFIG(0x007b)
#define CONFIG_TELSUN_S7Chan              __CTkvs_CONFIG(0x007c)
#define CONFIG_TELSUN_LinkCode            __CTkvs_CONFIG(0x007d)
#define CONFIG_TELSUN_LinkRate            __CTkvs_CONFIG(0x007e)
#define CONFIG_TELSUN_Reserve             __CTkvs_CONFIG(0x007f)
#define CONFIG_TELSUN_S7StackId           __CTkvs_CONFIG(0x0080)
// duplicate : #define CONFIG_TELSUN_LinkSet    __CTkvs_CONFIG(0x0081)
#define CONFIG_TELSUN_APC                 __CTkvs_CONFIG(0x0082)
#define CONFIG_TELSUN_SS7Dest             __CTkvs_CONFIG(0x0083)
#define CONFIG_TELSUN_SS7Rout             __CTkvs_CONFIG(0x0084)
#define CONFIG_TELSUN_LinkSet             __CTkvs_CONFIG(0x0085)
#define CONFIG_TELSUN_SS7Prio             __CTkvs_CONFIG(0x0086)
#define CONFIG_TELSUN_S7Slot              __CTkvs_CONFIG(0x0087)
#define CONFIG_TELSUN_OPC                 __CTkvs_CONFIG(0x0088)
#define CONFIG_TELSUN_ModuleNum           __CTkvs_CONFIG(0x0089)
#define CONFIG_TELSUN_ModuleData          __CTkvs_CONFIG(0x008a)
#define CONFIG_TELSUN_CardType            __CTkvs_CONFIG(0x008b)
#define CONFIG_TELSUN_DialType            __CTkvs_CONFIG(0x008c)
#define CONFIG_TELSUN_DialValue           __CTkvs_CONFIG(0x008d)
#define CONFIG_TELSUN_PrioMode1           __CTkvs_CONFIG(0x008e)
#define CONFIG_TELSUN_PrioMode2           __CTkvs_CONFIG(0x008f)
#define CONFIG_TELSUN_PrioMode3           __CTkvs_CONFIG(0x0090)
#define CONFIG_TELSUN_PrioMode4           __CTkvs_CONFIG(0x0091)
#define CONFIG_TELSUN_PrioMode5           __CTkvs_CONFIG(0x0092)
#define CONFIG_TELSUN_ConfType            __CTkvs_CONFIG(0x0093)
#define CONFIG_TELSUN_SysData             __CTkvs_CONFIG(0x0094)
#define CONFIG_TELSUN_T1Format            __CTkvs_CONFIG(0x0095)
#define CONFIG_TELSUN_T1Line              __CTkvs_CONFIG(0x0096)
#define CONFIG_TELSUN_Tag                 __CTkvs_CONFIG(0x0097)
#define CONFIG_TELSUN_Year                __CTkvs_CONFIG(0x0098)
#define CONFIG_TELSUN_Month               __CTkvs_CONFIG(0x0099)
#define CONFIG_TELSUN_Day                 __CTkvs_CONFIG(0x009a)
#define CONFIG_TELSUN_Hour                __CTkvs_CONFIG(0x009b)
#define CONFIG_TELSUN_Minute              __CTkvs_CONFIG(0x009c)
#define CONFIG_TELSUN_Second              __CTkvs_CONFIG(0x009d)
#define CONFIG_TELSUN_SignType            __CTkvs_CONFIG(0x009e)
#define CONFIG_TELSUN_TrunkType           __CTkvs_CONFIG(0x00a1)
#define CONFIG_TELSUN_IP_Matrix           __CTkvs_CONFIG(0x00a2)
#define CONFIG_TELSUN_Channels            __CTkvs_CONFIG(0X00aa)
#define CONFIG_TELSUN_ChannelStatus       __CTkvs_CONFIG(0X00ab)

#define CONFIG_TELSUN_swiNodeId            __CTkvs_CONFIG(0x00ac)
#define CONFIG_TELSUN_swiLogicSpans        __CTkvs_CONFIG(0x00ad)
#define CONFIG_TELSUN_swiChannelSpan       __CTkvs_CONFIG(0x00ae)
#define CONFIG_TELSUN_swiData              __CTkvs_CONFIG(0x00af)

#define CONFIG_TELSUN_LinkID		__CTkvs_CONFIG(0x00b0)
#define CONFIG_TELSUN_SignalValue	__CTkvs_CONFIG(0x00b1)
#define CONFIG_TELSUN_TransmisMOde	__CTkvs_CONFIG(0x00b2)
#define CONFIG_TELSUN_PPLEntityID	__CTkvs_CONFIG(0x00b3)
#define CONFIG_TELSUN_DistantReleaseMode	__CTkvs_CONFIG(0x00b4)
#define CONFIG_TELSUN_LocalReleaseMode		__CTkvs_CONFIG(0x00b5)



/******************************************************************************
 *    defined communication key.
 *****************************************************************************/

#define __CTCommSym(item)              CTsym_Build( CT_objCOMMUNICATION,\
						    CT_vendTELSUN,\
						    (item) )

#define Comm_TELSUN_Priority      __CTCommSym(0x001)
#define Comm_TELSUN_MsgKey        __CTCommSym(0x002)
#define Comm_TELSUN_ShmKey        __CTCommSym(0x003)
#define Comm_TELSUN_ShmSize       __CTCommSym(0x004)
#define Comm_TELSUN_DataOffset    __CTCommSym(0x005)
#define Comm_TELSUN_ClientData    __CTCommSym(0x006)
#define Comm_TELSUN_ClientQueueCount __CTCommSym(0x007)
#define Comm_TELSUN_MainQueueCount __CTCommSym(0x008)
#define Comm_TELSUN_TCPMsgKey      __CTCommSym(0x009)
//-------------------------   add by zg  10/22/98
#define Comm_TELSUN_MsgJudgeOffset      __CTCommSym(0x00a)


/******************************************************************************
 * defined profile module key. (Please let Walker Gun2 modified these )
 *****************************************************************************/
#define __CTCfgKeySym(item)             CTsym_Build( CT_objPROFILE,\
						  CT_vendTELSUN,\
						  (item))

#define Config_TELSUN_NullValue                 __CTCfgKeySym(0x000)
#define Config_TELSUN_APPLICATION_SERVICE       __CTCfgKeySym(0x001)
#define Config_TELSUN_ASIMap                    __CTCfgKeySym(0x002)
#define Config_TELSUN_CCR                       __CTCfgKeySym(0x003)
#define Config_TELSUN_CCRONLY                   __CTCfgKeySym(0x004)
#define Config_TELSUN_DEFAULT_CONFIGURATION     __CTCfgKeySym(0x005)
#define Config_TELSUN_FAX                       __CTCfgKeySym(0x006)
#define Config_TELSUN_GROUP_SET                 __CTCfgKeySym(0x007)
#define Config_TELSUN_NONE                      __CTCfgKeySym(0x008)
#define Config_TELSUN_PLAYER                    __CTCfgKeySym(0x009)
#define Config_TELSUN_PRIMARY_RESOURCE          __CTCfgKeySym(0x00a)
#define Config_TELSUN_RECORDER                  __CTCfgKeySym(0x00b)
#define Config_TELSUN_SIGD                      __CTCfgKeySym(0x00c)
#define Config_TELSUN_SIGG                      __CTCfgKeySym(0x00d)
#define Config_TELSUN_SPCTable                  __CTCfgKeySym(0x00e)
#define Config_TELSUN_UserDefinedID             __CTCfgKeySym(0x00f)
#define Config_TELSUN_FirstParam                __CTCfgKeySym(0x010)
#define Config_TELSUN_LastParam                 __CTCfgKeySym(0x02f)
#define Config_TELSUN_End                       __CTCfgKeySym(0x100)
#define Config_TELSUN_Delimit                   __CTCfgKeySym(0x101)
#define Config_TELSUN_Number                    __CTCfgKeySym(0x102)
#define Config_TELSUN_ValidKey                  __CTCfgKeySym(0x200)
#define Config_TELSUN_ASI                       __CTCfgKeySym(0x201)
#define Config_TELSUN_ASIInfo                   __CTCfgKeySym(0x204)
#define Config_TELSUN_PhoneNumber               __CTCfgKeySym(0x205)
#define Config_TELSUN_NetDev                    __CTCfgKeySym(0x206)
#define Config_TELSUN_VocDev                    __CTCfgKeySym(0x207)
#define Config_TELSUN_SubDevType                __CTCfgKeySym(0x208)
#define Config_TELSUN_SPCTableInfo              __CTCfgKeySym(0x209)

/******************************************************************************
 * defined SIA and CTFunction modules key.(Please remind Walker when modified )
 *****************************************************************************/
#define __CTSIAKeySym(item)             CTsym_Build( CT_objSIA,\
						  CT_vendTELSUN,\
                                                  (item) )

#define SIA_TELSUN_SessionID                    __CTCfgKeySym(0x001)
#define SIA_TELSUN_TraceResultString		__CTCfgKeySym(0x002)
#define SIA_TELSUN_StateArray                   __CTCfgKeySym(0x003)

/******************************************************************************
 * defined Authen (Please remind Walker when modified )
 *****************************************************************************/
#define __CTAuthenKeySym(item)             CTsym_Build( CT_objAUTHEN,\
						  CT_vendTELSUN,\
                                                  (item) )

#define Authen_TELSUN_MailBoxNo                    __CTAuthenKeySym(0x001)
#define Authen_TELSUN_VerifyFlag                   __CTAuthenKeySym(0x002)
#define Authen_TELSUN_NotifyType                   __CTAuthenKeySym(0x003)
#define Authen_TELSUN_NotifyNo                     __CTAuthenKeySym(0x004)
#define Authen_TELSUN_SubMailBoxNo                 __CTAuthenKeySym(0x005)
#define Authen_TELSUN_Password                     __CTAuthenKeySym(0x006) 
#define Authen_TELSUN_MailBoxPath                  __CTAuthenKeySym(0x007)
#define Authen_TELSUN_MailNum                      __CTAuthenKeySym(0x008)
#define Authen_TELSUN_SubMailBoxNum                __CTAuthenKeySym(0x009)
#define Authen_TELSUN_ValidMaxMailNum              __CTAuthenKeySym(0x00a)
#define Authen_TELSUN_ValidMaxMailTime             __CTAuthenKeySym(0x00b)
#define Authen_TELSUN_FeeType                      __CTAuthenKeySym(0x00c)
#define Authen_TELSUN_Status                       __CTAuthenKeySym(0x00d)
#define Authen_TELSUN_Caller                       __CTAuthenKeySym(0x00f) 
#define Authen_TELSUN_Called                       __CTAuthenKeySym(0x010) 
#define Authen_TELSUN_ServiceStartTime             __CTAuthenKeySym(0x011) 
#define Authen_TELSUN_ServiceValidtime             __CTAuthenKeySym(0x012) 
#define Authen_TELSUN_VoxLength                    __CTAuthenKeySym(0x013) 
#define Authen_TELSUN_NewPassword                  __CTAuthenKeySym(0x014) 
#define Authen_TELSUN_AcceptType                   __CTAuthenKeySym(0x015) 
#define Authen_TELSUN_ServiceValidTime             __CTAuthenKeySym(0x016) 
#define Authen_TELSUN_NotifyStartTime              __CTAuthenKeySym(0x017)
#define Authen_TELSUN_NotifyEndTime                __CTAuthenKeySym(0x018)
#define Authen_TELSUN_NotifyIndex                  __CTAuthenKeySym(0x019)

#define Authen_TELSUN_SrvCmdMsgTotal               __CTAuthenKeySym(0x100) 
#define Authen_TELSUN_SrvCmdMsgUnknown             __CTAuthenKeySym(0x101) 

#define Authen_TELSUN_SrvCmdMsgAccount             __CTAuthenKeySym(0x110) 
#define Authen_TELSUN_SrvCmdMsgVerify              __CTAuthenKeySym(0x112) 
#define Authen_TELSUN_SrvCmdMsgChangePassword      __CTAuthenKeySym(0x114) 
#define Authen_TELSUN_SrvCmdMsgSetNotify           __CTAuthenKeySym(0x115) 
#define Authen_TELSUN_SrvCmdMsgSchedule            __CTAuthenKeySym(0x116) 
#define Authen_TELSUN_SrvCmdMsgGetNotify           __CTAuthenKeySym(0x117) 

#define Authen_TELSUN_ClnCmdMsgTotal               __CTAuthenKeySym(0x200)
#define Authen_TELSUN_ClnCmdMsgUnknown             __CTAuthenKeySym(0x201)
#define Authen_TELSUN_ClnRespMsgUnknown            __CTAuthenKeySym(0x202)
#define Authen_TELSUN_ClnCmdMsgPollInterval        __CTAuthenKeySym(0x203)
#define Authen_TELSUN_ClnRespMsgPollInterval       __CTAuthenKeySym(0x204)

#define Authen_TELSUN_ClnCmdMsgAccount              __CTAuthenKeySym(0x210)
#define Authen_TELSUN_ClnRespMsgSuccAccount         __CTAuthenKeySym(0x211)
#define Authen_TELSUN_ClnRespMsgFailAccount         __CTAuthenKeySym(0x212)
#define Authen_TELSUN_ClnCmdMsgVerify               __CTAuthenKeySym(0x213)
#define Authen_TELSUN_ClnRespMsgSuccVerify          __CTAuthenKeySym(0x214)
#define Authen_TELSUN_ClnRespMsgFailVerify          __CTAuthenKeySym(0x215)
#define Authen_TELSUN_ClnCmdMsgChangePassword       __CTAuthenKeySym(0x216)
#define Authen_TELSUN_ClnRespMsgSuccChangePassword  __CTAuthenKeySym(0x217)
#define Authen_TELSUN_ClnRespMsgFailChangePassword  __CTAuthenKeySym(0x218)
#define Authen_TELSUN_ClnCmdMsgSetNotify            __CTAuthenKeySym(0x219)
#define Authen_TELSUN_ClnRespMsgSuccSetNotify       __CTAuthenKeySym(0x21a)
#define Authen_TELSUN_ClnRespMsgFailSetNotify       __CTAuthenKeySym(0x21b)
#define Authen_TELSUN_ClnCmdMsgGetNotify            __CTAuthenKeySym(0x21c)
#define Authen_TELSUN_ClnRespMsgSuccGetNotify       __CTAuthenKeySym(0x21d)
#define Authen_TELSUN_ClnRespMsgFailGetNotify       __CTAuthenKeySym(0x21e)

/******************************************************************************
 * defined Scheduler (Please remind Walker when modified )
 *****************************************************************************/
#define __CTSchedulerKeySym(item)                CTsym_Build( CT_objSCHEDULER,\
                                                              CT_vendTELSUN,\
                                                              (item) )
#define Scheduler_TELSUN_Unknown                     __CTSchedulerKeySym(0x001)
#define Scheduler_TELSUN_TimerReceived               __CTSchedulerKeySym(0x002)
#define Scheduler_TELSUN_CmdAuthen                   __CTSchedulerKeySym(0x003)
#define Scheduler_TELSUN_RespAuthen                  __CTSchedulerKeySym(0x004)
#define Scheduler_TELSUN_CmdSCR                      __CTSchedulerKeySym(0x005)
#define Scheduler_TELSUN_RespSCR                     __CTSchedulerKeySym(0x006)

#define Scheduler_TELSUN_RecordCount                 __CTSchedulerKeySym(0x010)
#define Scheduler_TELSUN_RecordArray                 __CTSchedulerKeySym(0x011)
#define Scheduler_TELSUN_ArrayIndex                  __CTSchedulerKeySym(0x012)
#define Scheduler_TELSUN_Caller                      __CTSchedulerKeySym(0x013)
#define Scheduler_TELSUN_Called                      __CTSchedulerKeySym(0x014)
#define Scheduler_TELSUN_StartTime                   __CTSchedulerKeySym(0x015)
#define Scheduler_TELSUN_EndTime                     __CTSchedulerKeySym(0x016)
#define Scheduler_TELSUN_NotifyWay                   __CTSchedulerKeySym(0x017)

#endif

