#ifndef __SS7EVT__H__
#define __SS7EVT__H__

#define   SS7_TUP_IAM	 0		
#define   SS7_TUP_IAI    1
#define   SS7_TUP_SAM    2
#define   SS7_TUP_SAO    3
#define   SS7_TUP_ACM    4
#define   SS7_TUP_ANC    5
#define   SS7_TUP_ANN    6
#define   SS7_TUP_ANU    7
#define   SS7_TUP_CBK    8
#define   SS7_TUP_CLF    9
#define   SS7_TUP_RLG    10
#define   SS7_TUP_GRQ    11
#define   SS7_TUP_GSM    12
#define   SS7_TUP_RAN    13
#define   SS7_TUP_FOT    14
#define   SS7_TUP_CCL    15
#define   SS7_TUP_CFL    16
#define   SS7_TUP_ACB    17
#define   SS7_TUP_ACC    18
#define   SS7_TUP_ADI    19
#define   SS7_TUP_CGC    20
#define   SS7_TUP_DPN    21
#define   SS7_TUP_LOS    22
#define   SS7_TUP_NNC    23
#define   SS7_TUP_SEC    24
#define   SS7_TUP_SSB    25
#define   SS7_TUP_SST    26
#define   SS7_TUP_OPR    27
#define   SS7_TUP_EUM    28
#define   SS7_TUP_UNN    29
#define   SS7_TUP_CCR    30
#define   SS7_TUP_COT    31
#define   SS7_TUP_CCF    32
#define   SS7_TUP_GRS    33
#define   SS7_TUP_GRA    34
#define   SS7_TUP_RSC    35
#define   SS7_TUP_BLO    36
#define   SS7_TUP_BLA    37
#define   SS7_TUP_UBL    38
#define   SS7_TUP_UBA    39
#define   SS7_TUP_MGB    40
#define   SS7_TUP_MBA    41
#define   SS7_TUP_MGU    42
#define   SS7_TUP_MUA    43
#define   SS7_TUP_HGB    44
#define   SS7_TUP_HBA    45
#define   SS7_TUP_HGU    46
#define   SS7_TUP_HUA    47
#define   SS7_TUP_SGB    48
#define   SS7_TUP_SBA    49
#define   SS7_TUP_SGU    50
#define   SS7_TUP_SUA    51
#define   SS7_TUP_MPM	 52
#define   SS7_TUP_SLB	 53
#define   SS7_TUP_STB	 54
#define   SS7_TUP_MAL	 55
#define   SS7_TUP_CHG	 56
#define   SS7_TUP_CRCM	 0x80	// 呼叫释放控制方式
#define   SS7_TUP_CCC	 0x81


#endif
